var searchData=
[
  ['i2c_0',['I2C',['../classperipherals_1_1_i2_c.html',1,'peripherals']]],
  ['i2c_5farduino_1',['I2C_Arduino',['../classperipherals_1_1_i2_c___arduino.html',1,'peripherals']]],
  ['i2s_5fnrf52840_2',['I2S_nrf52840',['../classperipherals_1_1_i2_s__nrf52840.html',1,'peripherals']]],
  ['iaudiocodec_3',['IAudioCodec',['../classperipherals_1_1_i_audio_codec.html',1,'peripherals']]],
  ['iaudioi2s_4',['IAudioI2S',['../classperipherals_1_1_i_audio_i2_s.html',1,'peripherals']]],
  ['icb_5ftype_5',['ICB_Type',['../struct_i_c_b___type.html',1,'']]],
  ['id_5fr_6',['id_r',['../structid__r.html',1,'']]],
  ['ifm2_5fbase0_5fr_7',['ifm2_base0_r',['../structifm2__base0__r.html',1,'']]],
  ['ifm2_5fbase1_5fr_8',['ifm2_base1_r',['../structifm2__base1__r.html',1,'']]],
  ['ifm2_5fbase2_5fr_9',['ifm2_base2_r',['../structifm2__base2__r.html',1,'']]],
  ['ifm2_5fbase3_5fr_10',['ifm2_base3_r',['../structifm2__base3__r.html',1,'']]],
  ['ifm2_5fbroadcast_5fr_11',['ifm2_broadcast_r',['../structifm2__broadcast__r.html',1,'']]],
  ['ifm2_5fheight0_5fm1_5fr_12',['ifm2_height0_m1_r',['../structifm2__height0__m1__r.html',1,'']]],
  ['ifm2_5fheight1_5fm1_5fr_13',['ifm2_height1_m1_r',['../structifm2__height1__m1__r.html',1,'']]],
  ['ifm2_5fib_5fstart_5fr_14',['ifm2_ib_start_r',['../structifm2__ib__start__r.html',1,'']]],
  ['ifm2_5fprecision_5fr_15',['ifm2_precision_r',['../structifm2__precision__r.html',1,'']]],
  ['ifm2_5fregion_5fr_16',['ifm2_region_r',['../structifm2__region__r.html',1,'']]],
  ['ifm2_5fscalar_5fr_17',['ifm2_scalar_r',['../structifm2__scalar__r.html',1,'']]],
  ['ifm2_5fstride_5fc_5fr_18',['ifm2_stride_c_r',['../structifm2__stride__c__r.html',1,'']]],
  ['ifm2_5fstride_5fx_5fr_19',['ifm2_stride_x_r',['../structifm2__stride__x__r.html',1,'']]],
  ['ifm2_5fstride_5fy_5fr_20',['ifm2_stride_y_r',['../structifm2__stride__y__r.html',1,'']]],
  ['ifm2_5fwidth0_5fm1_5fr_21',['ifm2_width0_m1_r',['../structifm2__width0__m1__r.html',1,'']]],
  ['ifm2_5fzero_5fpoint_5fr_22',['ifm2_zero_point_r',['../structifm2__zero__point__r.html',1,'']]],
  ['ifm_5fbase0_5fr_23',['ifm_base0_r',['../structifm__base0__r.html',1,'']]],
  ['ifm_5fbase1_5fr_24',['ifm_base1_r',['../structifm__base1__r.html',1,'']]],
  ['ifm_5fbase2_5fr_25',['ifm_base2_r',['../structifm__base2__r.html',1,'']]],
  ['ifm_5fbase3_5fr_26',['ifm_base3_r',['../structifm__base3__r.html',1,'']]],
  ['ifm_5fcblk_5fdepth_5fm1_5fr_27',['ifm_cblk_depth_m1_r',['../structifm__cblk__depth__m1__r.html',1,'']]],
  ['ifm_5fcblk_5fheight_5fr_28',['ifm_cblk_height_r',['../structifm__cblk__height__r.html',1,'']]],
  ['ifm_5fcblk_5fwidth_5fr_29',['ifm_cblk_width_r',['../structifm__cblk__width__r.html',1,'']]],
  ['ifm_5fdepth_5fm1_5fr_30',['ifm_depth_m1_r',['../structifm__depth__m1__r.html',1,'']]],
  ['ifm_5fheight0_5fm1_5fr_31',['ifm_height0_m1_r',['../structifm__height0__m1__r.html',1,'']]],
  ['ifm_5fheight1_5fm1_5fr_32',['ifm_height1_m1_r',['../structifm__height1__m1__r.html',1,'']]],
  ['ifm_5fib_5fend_5fr_33',['ifm_ib_end_r',['../structifm__ib__end__r.html',1,'']]],
  ['ifm_5fpad_5fbottom_5fr_34',['ifm_pad_bottom_r',['../structifm__pad__bottom__r.html',1,'']]],
  ['ifm_5fpad_5fleft_5fr_35',['ifm_pad_left_r',['../structifm__pad__left__r.html',1,'']]],
  ['ifm_5fpad_5fright_5fr_36',['ifm_pad_right_r',['../structifm__pad__right__r.html',1,'']]],
  ['ifm_5fpad_5ftop_5fr_37',['ifm_pad_top_r',['../structifm__pad__top__r.html',1,'']]],
  ['ifm_5fprecision_5fr_38',['ifm_precision_r',['../structifm__precision__r.html',1,'']]],
  ['ifm_5fregion_5fr_39',['ifm_region_r',['../structifm__region__r.html',1,'']]],
  ['ifm_5fstride_5fc_5fr_40',['ifm_stride_c_r',['../structifm__stride__c__r.html',1,'']]],
  ['ifm_5fstride_5fx_5fr_41',['ifm_stride_x_r',['../structifm__stride__x__r.html',1,'']]],
  ['ifm_5fstride_5fy_5fr_42',['ifm_stride_y_r',['../structifm__stride__y__r.html',1,'']]],
  ['ifm_5fupscale_5fr_43',['ifm_upscale_r',['../structifm__upscale__r.html',1,'']]],
  ['ifm_5fwidth0_5fm1_5fr_44',['ifm_width0_m1_r',['../structifm__width0__m1__r.html',1,'']]],
  ['ifm_5fz_5fr_45',['ifm_z_r',['../structifm__z__r.html',1,'']]],
  ['ifm_5fzero_5fpoint_5fr_46',['ifm_zero_point_r',['../structifm__zero__point__r.html',1,'']]],
  ['ifoptions_47',['IfOptions',['../classschema__py__generated_1_1_if_options.html',1,'schema_py_generated']]],
  ['ifoptionsbuilder_48',['IfOptionsBuilder',['../structtflite_1_1_if_options_builder.html',1,'tflite']]],
  ['ifoptionst_49',['IfOptionsT',['../classschema__py__generated_1_1_if_options_t.html',1,'schema_py_generated.IfOptionsT'],['../structtflite_1_1_if_options_t.html',1,'tflite::IfOptionsT']]],
  ['implsaturatingroundingmultiplybypot_50',['ImplSaturatingRoundingMultiplyByPOT',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t.html',1,'gemmlowp']]],
  ['implsaturatingroundingmultiplybypot_3c_20exponent_2c_20int16x8_5ft_2c_20_2d1_20_3e_51',['ImplSaturatingRoundingMultiplyByPOT&lt; Exponent, int16x8_t, -1 &gt;',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t_3_01_exponent_00_01int16x8__t_00_01-1_01_4.html',1,'gemmlowp']]],
  ['implsaturatingroundingmultiplybypot_3c_20exponent_2c_20int16x8_5ft_2c_201_20_3e_52',['ImplSaturatingRoundingMultiplyByPOT&lt; Exponent, int16x8_t, 1 &gt;',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t_3_01_exponent_00_01int16x8__t_00_011_01_4.html',1,'gemmlowp']]],
  ['implsaturatingroundingmultiplybypot_3c_20exponent_2c_20int32x4_5ft_2c_20_2d1_20_3e_53',['ImplSaturatingRoundingMultiplyByPOT&lt; Exponent, int32x4_t, -1 &gt;',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t_3_01_exponent_00_01int32x4__t_00_01-1_01_4.html',1,'gemmlowp']]],
  ['implsaturatingroundingmultiplybypot_3c_20exponent_2c_20int32x4_5ft_2c_201_20_3e_54',['ImplSaturatingRoundingMultiplyByPOT&lt; Exponent, int32x4_t, 1 &gt;',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t_3_01_exponent_00_01int32x4__t_00_011_01_4.html',1,'gemmlowp']]],
  ['implsaturatingroundingmultiplybypot_3c_20exponent_2c_20integertype_2c_20_2d1_20_3e_55',['ImplSaturatingRoundingMultiplyByPOT&lt; Exponent, IntegerType, -1 &gt;',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t_3_01_exponent_00_01_integer_type_00_01-1_01_4.html',1,'gemmlowp']]],
  ['implsaturatingroundingmultiplybypot_3c_20exponent_2c_20integertype_2c_200_20_3e_56',['ImplSaturatingRoundingMultiplyByPOT&lt; Exponent, IntegerType, 0 &gt;',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t_3_01_exponent_00_01_integer_type_00_010_01_4.html',1,'gemmlowp']]],
  ['implsaturatingroundingmultiplybypot_3c_20exponent_2c_20integertype_2c_201_20_3e_57',['ImplSaturatingRoundingMultiplyByPOT&lt; Exponent, IntegerType, 1 &gt;',['../structgemmlowp_1_1_impl_saturating_rounding_multiply_by_p_o_t_3_01_exponent_00_01_integer_type_00_011_01_4.html',1,'gemmlowp']]],
  ['inference_5ft_58',['inference_t',['../structinference__t.html',1,'']]],
  ['inonpersistentbufferallocator_59',['INonPersistentBufferAllocator',['../classtflite_1_1_i_non_persistent_buffer_allocator.html',1,'tflite']]],
  ['inputbuffer_60',['InputBuffer',['../structtest__over__serial_1_1_input_buffer.html',1,'test_over_serial']]],
  ['inputhandler_61',['InputHandler',['../classtest__over__serial_1_1_input_handler.html',1,'test_over_serial']]],
  ['int16x8_5fm128i_62',['int16x8_m128i',['../structgemmlowp_1_1int16x8__m128i.html',1,'gemmlowp']]],
  ['int32vector_63',['Int32Vector',['../classschema__py__generated_1_1_int32_vector.html',1,'schema_py_generated']]],
  ['int32vectorbuilder_64',['Int32VectorBuilder',['../structtflite_1_1_int32_vector_builder.html',1,'tflite']]],
  ['int32vectort_65',['Int32VectorT',['../classschema__py__generated_1_1_int32_vector_t.html',1,'schema_py_generated.Int32VectorT'],['../structtflite_1_1_int32_vector_t.html',1,'tflite::Int32VectorT']]],
  ['intarray_66',['IntArray',['../classutils_1_1_int_array.html',1,'utils']]],
  ['integerlstmparameter_67',['IntegerLstmParameter',['../structtflite_1_1ops_1_1micro_1_1lstm__eval_1_1_integer_lstm_parameter.html',1,'tflite::ops::micro::lstm_eval']]],
  ['integral_5fconstant_68',['integral_constant',['../structflatbuffers_1_1integral__constant.html',1,'flatbuffers']]],
  ['integral_5fconstant_3c_20bool_2c_20b_20_3e_69',['integral_constant&lt; bool, B &gt;',['../structflatbuffers_1_1integral__constant.html',1,'flatbuffers']]],
  ['intergateparameters_70',['InterGateParameters',['../structtflite_1_1_inter_gate_parameters.html',1,'tflite']]],
  ['interpreter_71',['Interpreter',['../classtflite__micro_1_1runtime_1_1_interpreter.html',1,'tflite_micro::runtime']]],
  ['interpreterconfig_72',['InterpreterConfig',['../classtflite__micro_1_1runtime_1_1_interpreter_config.html',1,'tflite_micro::runtime']]],
  ['interpreterwrapper_73',['InterpreterWrapper',['../classtflite_1_1_interpreter_wrapper.html',1,'tflite']]],
  ['ipersistentbufferallocator_74',['IPersistentBufferAllocator',['../classtflite_1_1_i_persistent_buffer_allocator.html',1,'tflite']]],
  ['ipsr_5ftype_75',['IPSR_Type',['../union_i_p_s_r___type.html',1,'']]],
  ['irfftfloatstate_76',['IrfftFloatState',['../structtflite_1_1tflm__signal_1_1_irfft_float_state.html',1,'tflite::tflm_signal']]],
  ['irfftop_77',['IrfftOp',['../classtensorflow_1_1signal_1_1_irfft_op.html',1,'tensorflow::signal']]],
  ['is_5fenum_78',['is_enum',['../structflatbuffers_1_1is__enum.html',1,'flatbuffers']]],
  ['is_5ffloating_5fpoint_79',['is_floating_point',['../structflatbuffers_1_1is__floating__point.html',1,'flatbuffers']]],
  ['is_5fint32_5for_5fint64_80',['is_int32_or_int64',['../structtflite_1_1is__int32__or__int64.html',1,'tflite']]],
  ['is_5fsame_81',['is_same',['../structflatbuffers_1_1is__same.html',1,'flatbuffers']]],
  ['is_5fscalar_82',['is_scalar',['../structflatbuffers_1_1is__scalar.html',1,'flatbuffers']]],
  ['is_5fsmall_5finteger_83',['is_small_integer',['../structtflite_1_1is__small__integer.html',1,'tflite']]],
  ['is_5funsigned_84',['is_unsigned',['../structflatbuffers_1_1is__unsigned.html',1,'flatbuffers']]],
  ['itm_5ftype_85',['ITM_Type',['../struct_i_t_m___type.html',1,'']]]
];
