var searchData=
[
  ['fakemicrocontext_0',['FakeMicroContext',['../classtflite_1_1_fake_micro_context.html',1,'tflite']]],
  ['fakequantoptions_1',['FakeQuantOptions',['../classschema__py__generated_1_1_fake_quant_options.html',1,'schema_py_generated']]],
  ['fakequantoptionsbuilder_2',['FakeQuantOptionsBuilder',['../structtflite_1_1_fake_quant_options_builder.html',1,'tflite']]],
  ['fakequantoptionst_3',['FakeQuantOptionsT',['../classschema__py__generated_1_1_fake_quant_options_t.html',1,'schema_py_generated.FakeQuantOptionsT'],['../structtflite_1_1_fake_quant_options_t.html',1,'tflite::FakeQuantOptionsT']]],
  ['fakequantparams_4',['FakeQuantParams',['../structtflite_1_1_fake_quant_params.html',1,'tflite']]],
  ['feature_5',['feature',['../classei_1_1spectral_1_1feature.html',1,'ei::spectral::feature'],['../classei_1_1speechpy_1_1feature.html',1,'ei::speechpy::feature']]],
  ['featureparams_6',['FeatureParams',['../classaudio__preprocessor_1_1_feature_params.html',1,'audio_preprocessor']]],
  ['featureprovider_7',['FeatureProvider',['../class_feature_provider.html',1,'']]],
  ['fft_5fcomplex_5fi32_5ft_8',['fft_complex_i32_t',['../structfft__complex__i32__t.html',1,'']]],
  ['fft_5fcomplex_5ft_9',['fft_complex_t',['../structfft__complex__t.html',1,'']]],
  ['fftautoscaleop_10',['FftAutoScaleOp',['../classtensorflow_1_1signal_1_1_fft_auto_scale_op.html',1,'tensorflow::signal']]],
  ['fftstate_11',['FftState',['../struct_fft_state.html',1,'']]],
  ['fieldloc_12',['FieldLoc',['../structflatbuffers_1_1_flat_buffer_builder_1_1_field_loc.html',1,'flatbuffers::FlatBufferBuilder']]],
  ['filloptions_13',['FillOptions',['../classschema__py__generated_1_1_fill_options.html',1,'schema_py_generated']]],
  ['filloptionsbuilder_14',['FillOptionsBuilder',['../structtflite_1_1_fill_options_builder.html',1,'tflite']]],
  ['filloptionst_15',['FillOptionsT',['../classschema__py__generated_1_1_fill_options_t.html',1,'schema_py_generated.FillOptionsT'],['../structtflite_1_1_fill_options_t.html',1,'tflite::FillOptionsT']]],
  ['filterbankconfig_16',['FilterbankConfig',['../struct_filterbank_config.html',1,'FilterbankConfig'],['../structtflite_1_1tflm__signal_1_1_filterbank_config.html',1,'tflite::tflm_signal::FilterbankConfig']]],
  ['filterbanklogop_17',['FilterBankLogOp',['../classtensorflow_1_1signal_1_1_filter_bank_log_op.html',1,'tensorflow::signal']]],
  ['filterbankop_18',['FilterBankOp',['../classtensorflow_1_1signal_1_1_filter_bank_op.html',1,'tensorflow::signal']]],
  ['filterbankoptest_19',['FilterBankOpTest',['../classtflite__micro_1_1signal_1_1ops_1_1filter__bank__ops__test_1_1_filter_bank_op_test.html',1,'tflite_micro::signal::ops::filter_bank_ops_test']]],
  ['filterbankspectralsubtractionop_20',['FilterBankSpectralSubtractionOp',['../classtensorflow_1_1signal_1_1_filter_bank_spectral_subtraction_op.html',1,'tensorflow::signal']]],
  ['filterbanksquarerootop_21',['FilterBankSquareRootOp',['../classtensorflow_1_1signal_1_1_filter_bank_square_root_op.html',1,'tensorflow::signal']]],
  ['filterbankstate_22',['FilterbankState',['../struct_filterbank_state.html',1,'']]],
  ['filtertest_23',['FilterTest',['../classexpand__stamp__vars__test_1_1_filter_test.html',1,'expand_stamp_vars_test']]],
  ['fir_5ffilter_24',['fir_filter',['../classfir__filter.html',1,'']]],
  ['fixedpoint_25',['FixedPoint',['../classgemmlowp_1_1_fixed_point.html',1,'gemmlowp']]],
  ['fixedpointrawtypetraits_26',['FixedPointRawTypeTraits',['../structgemmlowp_1_1_fixed_point_raw_type_traits.html',1,'gemmlowp']]],
  ['fixedpointrawtypetraits_3c_20_5f_5fm128i_20_3e_27',['FixedPointRawTypeTraits&lt; __m128i &gt;',['../structgemmlowp_1_1_fixed_point_raw_type_traits_3_01____m128i_01_4.html',1,'gemmlowp']]],
  ['fixedpointrawtypetraits_3c_20int16x8_5fm128i_20_3e_28',['FixedPointRawTypeTraits&lt; int16x8_m128i &gt;',['../structgemmlowp_1_1_fixed_point_raw_type_traits_3_01int16x8__m128i_01_4.html',1,'gemmlowp']]],
  ['fixedpointrawtypetraits_3c_20int16x8_5ft_20_3e_29',['FixedPointRawTypeTraits&lt; int16x8_t &gt;',['../structgemmlowp_1_1_fixed_point_raw_type_traits_3_01int16x8__t_01_4.html',1,'gemmlowp']]],
  ['fixedpointrawtypetraits_3c_20int32x4_5ft_20_3e_30',['FixedPointRawTypeTraits&lt; int32x4_t &gt;',['../structgemmlowp_1_1_fixed_point_raw_type_traits_3_01int32x4__t_01_4.html',1,'gemmlowp']]],
  ['fixedpointrawtypetraits_3c_20std_3a_3aint16_5ft_20_3e_31',['FixedPointRawTypeTraits&lt; std::int16_t &gt;',['../structgemmlowp_1_1_fixed_point_raw_type_traits_3_01std_1_1int16__t_01_4.html',1,'gemmlowp']]],
  ['fixedpointrawtypetraits_3c_20std_3a_3aint32_5ft_20_3e_32',['FixedPointRawTypeTraits&lt; std::int32_t &gt;',['../structgemmlowp_1_1_fixed_point_raw_type_traits_3_01std_1_1int32__t_01_4.html',1,'gemmlowp']]],
  ['fixedtypedvector_33',['FixedTypedVector',['../classflexbuffers_1_1_fixed_typed_vector.html',1,'flexbuffers']]],
  ['flatbufferbuilder_34',['FlatBufferBuilder',['../classflatbuffers_1_1_flat_buffer_builder.html',1,'flatbuffers']]],
  ['flatbuffers_5ffinal_5fclass_35',['FLATBUFFERS_FINAL_CLASS',['../classflatbuffers_1_1_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s.html',1,'flatbuffers::FLATBUFFERS_FINAL_CLASS&lt; T, Extent &gt;'],['../struct_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s.html',1,'FLATBUFFERS_FINAL_CLASS'],['../classflexbuffers_1_1_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s.html',1,'flexbuffers::FLATBUFFERS_FINAL_CLASS'],['../structtflite_1_1_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s.html',1,'tflite::FLATBUFFERS_FINAL_CLASS'],['../structtflm_1_1codegen_1_1preprocessor_1_1_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s.html',1,'tflm::codegen::preprocessor::FLATBUFFERS_FINAL_CLASS']]],
  ['flatbuffersizegraph_36',['FlatbufferSizeGraph',['../classflatbuffer__size__graph_1_1_flatbuffer_size_graph.html',1,'flatbuffer_size_graph']]],
  ['flatbuffersizetest_37',['FlatbufferSizeTest',['../classflatbuffer__size__test_1_1_flatbuffer_size_test.html',1,'flatbuffer_size_test']]],
  ['flatbuffersizewrapper_38',['FlatbufferSizeWrapper',['../classtflite_1_1_flatbuffer_size_wrapper.html',1,'tflite']]],
  ['flatten_5fclass_39',['flatten_class',['../classflatten__class.html',1,'']]],
  ['flexbufferwrapper_40',['FlexbufferWrapper',['../classtflite_1_1_flexbuffer_wrapper.html',1,'tflite']]],
  ['floordivoptions_41',['FloorDivOptions',['../classschema__py__generated_1_1_floor_div_options.html',1,'schema_py_generated']]],
  ['floordivoptionsbuilder_42',['FloorDivOptionsBuilder',['../structtflite_1_1_floor_div_options_builder.html',1,'tflite']]],
  ['floordivoptionst_43',['FloorDivOptionsT',['../classschema__py__generated_1_1_floor_div_options_t.html',1,'schema_py_generated.FloorDivOptionsT'],['../structtflite_1_1_floor_div_options_t.html',1,'tflite::FloorDivOptionsT']]],
  ['floormodoptions_44',['FloorModOptions',['../classschema__py__generated_1_1_floor_mod_options.html',1,'schema_py_generated']]],
  ['floormodoptionsbuilder_45',['FloorModOptionsBuilder',['../structtflite_1_1_floor_mod_options_builder.html',1,'tflite']]],
  ['floormodoptionst_46',['FloorModOptionsT',['../classschema__py__generated_1_1_floor_mod_options_t.html',1,'schema_py_generated.FloorModOptionsT'],['../structtflite_1_1_floor_mod_options_t.html',1,'tflite::FloorModOptionsT']]],
  ['fmat_47',['fmat',['../structei_1_1fmat.html',1,'ei']]],
  ['fnode_48',['FNode',['../classflatbuffer__size__graph_1_1_f_node.html',1,'flatbuffer_size_graph']]],
  ['fpu_5ftype_49',['FPU_Type',['../struct_f_p_u___type.html',1,'']]],
  ['framerop_50',['FramerOp',['../classtensorflow_1_1signal_1_1_framer_op.html',1,'tensorflow::signal']]],
  ['frameroptest_51',['FramerOpTest',['../classtflite__micro_1_1signal_1_1ops_1_1framer__op__test_1_1_framer_op_test.html',1,'tflite_micro::signal::ops::framer_op_test']]],
  ['freq2meltest_52',['Freq2MelTest',['../classfreq__to__mel__test_1_1_freq2_mel_test.html',1,'freq_to_mel_test']]],
  ['freq_5fpeak_5fi32_5ft_53',['freq_peak_i32_t',['../structei_1_1spectral_1_1processing_1_1freq__peak__i32__t.html',1,'ei::spectral::processing']]],
  ['freq_5fpeak_5ft_54',['freq_peak_t',['../structei_1_1spectral_1_1processing_1_1freq__peak__t.html',1,'ei::spectral::processing']]],
  ['frontendconfig_55',['FrontendConfig',['../struct_frontend_config.html',1,'']]],
  ['frontendoutput_56',['FrontendOutput',['../struct_frontend_output.html',1,'']]],
  ['frontendstate_57',['FrontendState',['../struct_frontend_state.html',1,'']]],
  ['fullyconnected_58',['FullyConnected',['../classfully__connected_1_1_fully_connected.html',1,'fully_connected']]],
  ['fullyconnectedoptions_59',['FullyConnectedOptions',['../classschema__py__generated_1_1_fully_connected_options.html',1,'schema_py_generated']]],
  ['fullyconnectedoptionsbuilder_60',['FullyConnectedOptionsBuilder',['../structtflite_1_1_fully_connected_options_builder.html',1,'tflite']]],
  ['fullyconnectedoptionst_61',['FullyConnectedOptionsT',['../classschema__py__generated_1_1_fully_connected_options_t.html',1,'schema_py_generated.FullyConnectedOptionsT'],['../structtflite_1_1_fully_connected_options_t.html',1,'tflite::FullyConnectedOptionsT']]],
  ['fullyconnectedoptionsweightsformat_62',['FullyConnectedOptionsWeightsFormat',['../classschema__py__generated_1_1_fully_connected_options_weights_format.html',1,'schema_py_generated']]],
  ['fullyconnectedparams_63',['FullyConnectedParams',['../structtflite_1_1_fully_connected_params.html',1,'tflite']]],
  ['functions_64',['functions',['../classei_1_1speechpy_1_1functions.html',1,'ei::speechpy']]]
];
