var searchData=
[
  ['i2c_2eh_0',['i2c.h',['../i2c_8h.html',1,'']]],
  ['i2c_5farduino_2ecpp_1',['i2c_arduino.cpp',['../i2c__arduino_8cpp.html',1,'']]],
  ['i2c_5farduino_2eh_2',['i2c_arduino.h',['../i2c__arduino_8h.html',1,'']]],
  ['i2s_5fnrf52840_2ecpp_3',['i2s_nrf52840.cpp',['../i2s__nrf52840_8cpp.html',1,'']]],
  ['i2s_5fnrf52840_2eh_4',['i2s_nrf52840.h',['../i2s__nrf52840_8h.html',1,'']]],
  ['ibuffer_5fallocator_2eh_5',['ibuffer_allocator.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src45574e27285f7a1dc9b878500f1f08a5.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mid99374c4a5c25d81bb89c7274eca4375.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2ibuffer__allocator_8h.html',1,'(Global Namespace)']]],
  ['if_2ecc_6',['if.cc',['../if_8cc.html',1,'']]],
  ['if_2ecpp_7',['if.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src10bd2bbdd226c15c9083078e49faa60e.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2if_8cpp.html',1,'(Global Namespace)']]],
  ['if_5ftest_2ecc_8',['if_test.cc',['../if__test_8cc.html',1,'']]],
  ['image_2ehpp_9',['image.hpp',['../image_8hpp.html',1,'']]],
  ['image_5fprovider_2ecc_10',['image_provider.cc',['../image__provider_8cc.html',1,'']]],
  ['image_5fprovider_2eh_11',['image_provider.h',['../tflite-micro-arduino-examples-main_2examples_2person__detection_2image__provider_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2micro_2examples_2person__detection_2image__provider_8h.html',1,'(Global Namespace)']]],
  ['image_5fprovider_5ftest_2ecc_12',['image_provider_test.cc',['../image__provider__test_8cc.html',1,'']]],
  ['imu_2eino_13',['IMU.ino',['../_i_m_u_8ino.html',1,'']]],
  ['imucapture_2eino_14',['IMUCapture.ino',['../_i_m_u_capture_8ino.html',1,'']]],
  ['imucapturemodel_2eino_15',['IMUCaptureModel.ino',['../_i_m_u_capture_model_8ino.html',1,'']]],
  ['inference_5fgenerator_2epy_16',['inference_generator.py',['../inference__generator_8py.html',1,'']]],
  ['inferenceallocatetensor_2ecpp_17',['InferenceAllocateTensor.cpp',['../_inference_allocate_tensor_8cpp.html',1,'']]],
  ['inferenceinputdata_2ecpp_18',['InferenceInputData.cpp',['../_inference_input_data_8cpp.html',1,'']]],
  ['inferenceloadingmodel_2ecpp_19',['InferenceLoadingModel.cpp',['../_inference_loading_model_8cpp.html',1,'']]],
  ['inferenceoutputdata_2ecpp_20',['InferenceOutputData.cpp',['../_inference_output_data_8cpp.html',1,'']]],
  ['inferencerunning_2ecpp_21',['InferenceRunning.cpp',['../_inference_running_8cpp.html',1,'']]],
  ['initializationcode_2eino_22',['InitializationCode.ino',['../_initialization_code_8ino.html',1,'']]],
  ['instrumentation_2eh_23',['instrumentation.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src91524cca2048a76cd38fbf9742036cb1.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2third__party_2ruy_2ruy_2profiler_2instrumentation_8h.html',1,'(Global Namespace)']]],
  ['integration_5ftests_2ecc_24',['integration_tests.cc',['../add_2integration__tests_8cc.html',1,'(Global Namespace)'],['../conv_2integration__tests_8cc.html',1,'(Global Namespace)'],['../leaky__relu_2integration__tests_8cc.html',1,'(Global Namespace)'],['../pad_2integration__tests_8cc.html',1,'(Global Namespace)'],['../quantize_2integration__tests_8cc.html',1,'(Global Namespace)'],['../strided__slice_2integration__tests_8cc.html',1,'(Global Namespace)'],['../sub_2integration__tests_8cc.html',1,'(Global Namespace)'],['../transpose__conv_2integration__tests_8cc.html',1,'(Global Namespace)']]],
  ['interfacecode_2epy_25',['InterfaceCode.py',['../_interface_code_8py.html',1,'']]],
  ['interpolation_5ffunctions_2eh_26',['interpolation_functions.h',['../interpolation__functions_8h.html',1,'']]],
  ['interpolation_5ffunctions_5ff16_2eh_27',['interpolation_functions_f16.h',['../interpolation__functions__f16_8h.html',1,'']]],
  ['interpreter_5fmemory_5ffootprint_2ecc_28',['interpreter_memory_footprint.cc',['../interpreter__memory__footprint_8cc.html',1,'']]],
  ['interpreter_5fwrapper_2ecc_29',['interpreter_wrapper.cc',['../interpreter__wrapper_8cc.html',1,'']]],
  ['interpreter_5fwrapper_2eh_30',['interpreter_wrapper.h',['../interpreter__wrapper_8h.html',1,'']]],
  ['irfft_2ecc_31',['irfft.cc',['../irfft_8cc.html',1,'']]],
  ['irfft_2eh_32',['irfft.h',['../micro_2kernels_2irfft_8h.html',1,'(Global Namespace)'],['../src_2irfft_8h.html',1,'(Global Namespace)']]],
  ['irfft_5ffloat_2ecc_33',['irfft_float.cc',['../irfft__float_8cc.html',1,'']]],
  ['irfft_5fint16_2ecc_34',['irfft_int16.cc',['../irfft__int16_8cc.html',1,'']]],
  ['irfft_5fint32_2ecc_35',['irfft_int32.cc',['../irfft__int32_8cc.html',1,'']]],
  ['iris_2epy_36',['Iris.py',['../_iris_8py.html',1,'']]],
  ['issue_5fon_5ferror_2epy_37',['issue_on_error.py',['../issue__on__error_8py.html',1,'']]]
];
