var searchData=
[
  ['face_5faccess_5finferencing_2eh_0',['Face_Access_inferencing.h',['../_face___access__inferencing_8h.html',1,'']]],
  ['face_5fdetection_2epy_1',['face_detection.py',['../face__detection_8py.html',1,'']]],
  ['facefilter_2epy_2',['FaceFilter.py',['../_face_filter_8py.html',1,'']]],
  ['facetracking_2epy_3',['FaceTracking.py',['../_face_tracking_8py.html',1,'']]],
  ['factory_2epy_4',['factory.py',['../factory_8py.html',1,'']]],
  ['fake_5fmicro_5fcontext_2ecc_5',['fake_micro_context.cc',['../fake__micro__context_8cc.html',1,'']]],
  ['fake_5fmicro_5fcontext_2ecpp_6',['fake_micro_context.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src1e5fbb3be239f547824b251d78600fe9.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2fake__micro__context_8cpp.html',1,'(Global Namespace)']]],
  ['fake_5fmicro_5fcontext_2eh_7',['fake_micro_context.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcec60a7d9eda8c731776a5636917d9ba4.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2fake__micro__context_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2fake__micro__context_8h.html',1,'(Global Namespace)']]],
  ['fake_5fmicro_5fcontext_5ftest_2ecc_8',['fake_micro_context_test.cc',['../fake__micro__context__test_8cc.html',1,'']]],
  ['fast_2ddct_2dfft_2ecpp_9',['fast-dct-fft.cpp',['../fast-dct-fft_8cpp.html',1,'']]],
  ['fast_2ddct_2dfft_2eh_10',['fast-dct-fft.h',['../fast-dct-fft_8h.html',1,'']]],
  ['fast_5fmath_5ffunctions_2eh_11',['fast_math_functions.h',['../fast__math__functions_8h.html',1,'']]],
  ['fast_5fmath_5ffunctions_5ff16_2eh_12',['fast_math_functions_f16.h',['../fast__math__functions__f16_8h.html',1,'']]],
  ['fb_5fallocator_2eh_13',['fb_allocator.h',['../fb__allocator_8h.html',1,'']]],
  ['fb_5farray_2eh_14',['fb_array.h',['../fb__array_8h.html',1,'']]],
  ['fb_5fbase_2eh_15',['fb_base.h',['../fb__base_8h.html',1,'']]],
  ['fb_5fbuffer_2eh_16',['fb_buffer.h',['../fb__buffer_8h.html',1,'']]],
  ['fb_5fbuffer_5fref_2eh_17',['fb_buffer_ref.h',['../fb__buffer__ref_8h.html',1,'']]],
  ['fb_5fdefault_5fallocator_2eh_18',['fb_default_allocator.h',['../fb__default__allocator_8h.html',1,'']]],
  ['fb_5fdetached_5fbuffer_2eh_19',['fb_detached_buffer.h',['../fb__detached__buffer_8h.html',1,'']]],
  ['fb_5fflatbuffer_5fbuilder_2eh_20',['fb_flatbuffer_builder.h',['../fb__flatbuffer__builder_8h.html',1,'']]],
  ['fb_5fstl_5femulation_2eh_21',['fb_stl_emulation.h',['../fb__stl__emulation_8h.html',1,'']]],
  ['fb_5fstring_2eh_22',['fb_string.h',['../fb__string_8h.html',1,'']]],
  ['fb_5fstruct_2eh_23',['fb_struct.h',['../fb__struct_8h.html',1,'']]],
  ['fb_5ftable_2eh_24',['fb_table.h',['../fb__table_8h.html',1,'']]],
  ['fb_5futil_2eh_25',['fb_util.h',['../fb__util_8h.html',1,'']]],
  ['fb_5fvector_2eh_26',['fb_vector.h',['../fb__vector_8h.html',1,'']]],
  ['fb_5fvector_5fdownward_2eh_27',['fb_vector_downward.h',['../fb__vector__downward_8h.html',1,'']]],
  ['fb_5fverifier_2eh_28',['fb_verifier.h',['../fb__verifier_8h.html',1,'']]],
  ['feature_2ehpp_29',['feature.hpp',['../spectral_2feature_8hpp.html',1,'(Global Namespace)'],['../speechpy_2feature_8hpp.html',1,'(Global Namespace)']]],
  ['feature_5fprovider_2ecpp_30',['feature_provider.cpp',['../feature__provider_8cpp.html',1,'']]],
  ['feature_5fprovider_2eh_31',['feature_provider.h',['../feature__provider_8h.html',1,'']]],
  ['fft_2ecc_32',['fft.cc',['../fft_8cc.html',1,'']]],
  ['fft_2ecpp_33',['fft.cpp',['../fft_8cpp.html',1,'']]],
  ['fft_2eh_34',['fft.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2fft_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2fft_8h.html',1,'(Global Namespace)']]],
  ['fft_5fauto_5fscale_2ecc_35',['fft_auto_scale.cc',['../fft__auto__scale_8cc.html',1,'']]],
  ['fft_5fauto_5fscale_2eh_36',['fft_auto_scale.h',['../fft__auto__scale_8h.html',1,'']]],
  ['fft_5fauto_5fscale_5fcommon_2ecc_37',['fft_auto_scale_common.cc',['../fft__auto__scale__common_8cc.html',1,'']]],
  ['fft_5fauto_5fscale_5fkernel_2ecc_38',['fft_auto_scale_kernel.cc',['../fft__auto__scale__kernel_8cc.html',1,'(Global Namespace)'],['../xtensa_2fft__auto__scale__kernel_8cc.html',1,'(Global Namespace)']]],
  ['fft_5fauto_5fscale_5fkernel_2eh_39',['fft_auto_scale_kernel.h',['../fft__auto__scale__kernel_8h.html',1,'']]],
  ['fft_5fflexbuffers_5fgenerated_5fdata_2ecc_40',['fft_flexbuffers_generated_data.cc',['../fft__flexbuffers__generated__data_8cc.html',1,'']]],
  ['fft_5fflexbuffers_5fgenerated_5fdata_2eh_41',['fft_flexbuffers_generated_data.h',['../fft__flexbuffers__generated__data_8h.html',1,'']]],
  ['fft_5fio_2ec_42',['fft_io.c',['../fft__io_8c.html',1,'']]],
  ['fft_5fio_2eh_43',['fft_io.h',['../fft__io_8h.html',1,'']]],
  ['fft_5fkernels_2ecc_44',['fft_kernels.cc',['../fft__kernels_8cc.html',1,'']]],
  ['fft_5fops_2ecc_45',['fft_ops.cc',['../fft__ops_8cc.html',1,'']]],
  ['fft_5fops_2epy_46',['fft_ops.py',['../fft__ops_8py.html',1,'']]],
  ['fft_5fops_5ftest_2epy_47',['fft_ops_test.py',['../fft__ops__test_8py.html',1,'']]],
  ['fft_5ftest_2ecc_48',['fft_test.cc',['../signal_2micro_2kernels_2fft__test_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2experimental_2microfrontend_2lib_2fft__test_8cc.html',1,'(Global Namespace)']]],
  ['fft_5ftest_5fdata_2ecc_49',['fft_test_data.cc',['../fft__test__data_8cc.html',1,'']]],
  ['fft_5ftest_5fdata_2eh_50',['fft_test_data.h',['../fft__test__data_8h.html',1,'']]],
  ['fft_5futil_2ecc_51',['fft_util.cc',['../fft__util_8cc.html',1,'']]],
  ['fft_5futil_2ecpp_52',['fft_util.cpp',['../fft__util_8cpp.html',1,'']]],
  ['fft_5futil_2eh_53',['fft_util.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2fft__util_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2fft__util_8h.html',1,'(Global Namespace)']]],
  ['fill_2ecc_54',['fill.cc',['../fill_8cc.html',1,'']]],
  ['fill_2ecpp_55',['fill.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src7519f0b6b251ab37db032086a706c21e.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2fill_8cpp.html',1,'(Global Namespace)']]],
  ['fill_2eh_56',['fill.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src7564b4e419dc227a650c2244113388b1.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke0baaa88fbffaab3054c680b02e5d8c1a.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2fill_8h.html',1,'(Global Namespace)']]],
  ['fill_5ftest_2ecc_57',['fill_test.cc',['../fill__test_8cc.html',1,'']]],
  ['filter_5fbank_2ecc_58',['filter_bank.cc',['../micro_2kernels_2filter__bank_8cc.html',1,'(Global Namespace)'],['../src_2filter__bank_8cc.html',1,'(Global Namespace)']]],
  ['filter_5fbank_2eh_59',['filter_bank.h',['../filter__bank_8h.html',1,'']]],
  ['filter_5fbank_5fflexbuffers_5fgenerated_5fdata_2ecc_60',['filter_bank_flexbuffers_generated_data.cc',['../filter__bank__flexbuffers__generated__data_8cc.html',1,'']]],
  ['filter_5fbank_5fflexbuffers_5fgenerated_5fdata_2eh_61',['filter_bank_flexbuffers_generated_data.h',['../filter__bank__flexbuffers__generated__data_8h.html',1,'']]],
  ['filter_5fbank_5fkernels_2ecc_62',['filter_bank_kernels.cc',['../filter__bank__kernels_8cc.html',1,'']]],
  ['filter_5fbank_5flog_2ecc_63',['filter_bank_log.cc',['../micro_2kernels_2filter__bank__log_8cc.html',1,'(Global Namespace)'],['../src_2filter__bank__log_8cc.html',1,'(Global Namespace)']]],
  ['filter_5fbank_5flog_2eh_64',['filter_bank_log.h',['../filter__bank__log_8h.html',1,'']]],
  ['filter_5fbank_5flog_5fflexbuffers_5fgenerated_5fdata_2ecc_65',['filter_bank_log_flexbuffers_generated_data.cc',['../filter__bank__log__flexbuffers__generated__data_8cc.html',1,'']]],
  ['filter_5fbank_5flog_5fflexbuffers_5fgenerated_5fdata_2eh_66',['filter_bank_log_flexbuffers_generated_data.h',['../filter__bank__log__flexbuffers__generated__data_8h.html',1,'']]],
  ['filter_5fbank_5flog_5ftest_2ecc_67',['filter_bank_log_test.cc',['../filter__bank__log__test_8cc.html',1,'']]],
  ['filter_5fbank_5fops_2ecc_68',['filter_bank_ops.cc',['../filter__bank__ops_8cc.html',1,'']]],
  ['filter_5fbank_5fops_2epy_69',['filter_bank_ops.py',['../filter__bank__ops_8py.html',1,'']]],
  ['filter_5fbank_5fops_5ftest_2epy_70',['filter_bank_ops_test.py',['../filter__bank__ops__test_8py.html',1,'']]],
  ['filter_5fbank_5fspectral_5fsubtraction_2ecc_71',['filter_bank_spectral_subtraction.cc',['../micro_2kernels_2filter__bank__spectral__subtraction_8cc.html',1,'(Global Namespace)'],['../src_2filter__bank__spectral__subtraction_8cc.html',1,'(Global Namespace)']]],
  ['filter_5fbank_5fspectral_5fsubtraction_2eh_72',['filter_bank_spectral_subtraction.h',['../filter__bank__spectral__subtraction_8h.html',1,'']]],
  ['filter_5fbank_5fspectral_5fsubtraction_5fflexbuffers_5fgenerated_5fdata_2ecc_73',['filter_bank_spectral_subtraction_flexbuffers_generated_data.cc',['../filter__bank__spectral__subtraction__flexbuffers__generated__data_8cc.html',1,'']]],
  ['filter_5fbank_5fspectral_5fsubtraction_5fflexbuffers_5fgenerated_5fdata_2eh_74',['filter_bank_spectral_subtraction_flexbuffers_generated_data.h',['../filter__bank__spectral__subtraction__flexbuffers__generated__data_8h.html',1,'']]],
  ['filter_5fbank_5fspectral_5fsubtraction_5ftest_2ecc_75',['filter_bank_spectral_subtraction_test.cc',['../filter__bank__spectral__subtraction__test_8cc.html',1,'']]],
  ['filter_5fbank_5fsquare_5froot_2ecc_76',['filter_bank_square_root.cc',['../micro_2kernels_2filter__bank__square__root_8cc.html',1,'(Global Namespace)'],['../micro_2kernels_2xtensa_2filter__bank__square__root_8cc.html',1,'(Global Namespace)'],['../src_2filter__bank__square__root_8cc.html',1,'(Global Namespace)']]],
  ['filter_5fbank_5fsquare_5froot_2eh_77',['filter_bank_square_root.h',['../micro_2kernels_2filter__bank__square__root_8h.html',1,'(Global Namespace)'],['../src_2filter__bank__square__root_8h.html',1,'(Global Namespace)']]],
  ['filter_5fbank_5fsquare_5froot_5fcommon_2ecc_78',['filter_bank_square_root_common.cc',['../filter__bank__square__root__common_8cc.html',1,'']]],
  ['filter_5fbank_5fsquare_5froot_5ftest_2ecc_79',['filter_bank_square_root_test.cc',['../filter__bank__square__root__test_8cc.html',1,'']]],
  ['filter_5fbank_5ftest_2ecc_80',['filter_bank_test.cc',['../filter__bank__test_8cc.html',1,'']]],
  ['filterbank_2ec_81',['filterbank.c',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank_8c.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank_8c.html',1,'(Global Namespace)']]],
  ['filterbank_2eh_82',['filterbank.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank_8h.html',1,'(Global Namespace)']]],
  ['filterbank_5fio_2ec_83',['filterbank_io.c',['../filterbank__io_8c.html',1,'']]],
  ['filterbank_5fio_2eh_84',['filterbank_io.h',['../filterbank__io_8h.html',1,'']]],
  ['filterbank_5ftest_2ecc_85',['filterbank_test.cc',['../filterbank__test_8cc.html',1,'']]],
  ['filterbank_5futil_2ec_86',['filterbank_util.c',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank__util_8c.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank__util_8c.html',1,'(Global Namespace)']]],
  ['filterbank_5futil_2eh_87',['filterbank_util.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank__util_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2filterbank__util_8h.html',1,'(Global Namespace)']]],
  ['filtering_5ffunctions_2eh_88',['filtering_functions.h',['../filtering__functions_8h.html',1,'']]],
  ['filtering_5ffunctions_5ff16_2eh_89',['filtering_functions_f16.h',['../filtering__functions__f16_8h.html',1,'']]],
  ['filters_2ehpp_90',['filters.hpp',['../filters_8hpp.html',1,'']]],
  ['findchessboardcorners_2epy_91',['FindChessboardCorners.py',['../_find_chessboard_corners_8py.html',1,'']]],
  ['fir_5ffilter_2ehpp_92',['fir_filter.hpp',['../fir__filter_8hpp.html',1,'']]],
  ['fix_5farduino_5fsubfolders_2epy_93',['fix_arduino_subfolders.py',['../fix__arduino__subfolders_8py.html',1,'']]],
  ['fixedpoint_2eh_94',['fixedpoint.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcbd0426898cca233a5356f2d5a6701844.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2third__party_2gemmlowp_2fixedpoint_2fixedpoint_8h.html',1,'(Global Namespace)']]],
  ['fixedpoint_5fneon_2eh_95',['fixedpoint_neon.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcb397fda51f958b9e4dadf76446eb4591.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2third__party_2gemmlowp_2fixedpoint_2fixedpoint__neon_8h.html',1,'(Global Namespace)']]],
  ['fixedpoint_5fsse_2eh_96',['fixedpoint_sse.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcb79d145fe7d1f3b5eb92e32d64b05dca.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2third__party_2gemmlowp_2fixedpoint_2fixedpoint__sse_8h.html',1,'(Global Namespace)']]],
  ['fixedpoint_5futils_2eh_97',['fixedpoint_utils.h',['../fixedpoint__utils_8h.html',1,'']]],
  ['flatbuffer_5fbuilder_2eh_98',['flatbuffer_builder.h',['../flatbuffer__builder_8h.html',1,'']]],
  ['flatbuffer_5fconversions_2ecc_99',['flatbuffer_conversions.cc',['../flatbuffer__conversions_8cc.html',1,'']]],
  ['flatbuffer_5fconversions_2ecpp_100',['flatbuffer_conversions.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcd4cb680552145761b6ff8b477fcca98e.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2core_2api_2flatbuffer__conversions_8cpp.html',1,'(Global Namespace)']]],
  ['flatbuffer_5fconversions_2eh_101',['flatbuffer_conversions.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src167c64a4a4965b1bc7eb7904bdf24db2.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2coe37dd6812122abb3b519aa77ddb965fe.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2core_2api_2flatbuffer__conversions_8h.html',1,'(Global Namespace)']]],
  ['flatbuffer_5fconversions_5fbridge_2ecc_102',['flatbuffer_conversions_bridge.cc',['../flatbuffer__conversions__bridge_8cc.html',1,'']]],
  ['flatbuffer_5fconversions_5fbridge_2ecpp_103',['flatbuffer_conversions_bridge.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src5123fab5d4d400b365c44fb6e6eeb2d1.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2flatbuffer__conversions__bridge_8cpp.html',1,'(Global Namespace)']]],
  ['flatbuffer_5fconversions_5fbridge_2eh_104',['flatbuffer_conversions_bridge.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcfe845b55c9fb50d49490a9d24936256f.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mi21c979363aac29bf31d5e1c50521a5c2.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2flatbuffer__conversions__bridge_8h.html',1,'(Global Namespace)']]],
  ['flatbuffer_5fsize_2ecc_105',['flatbuffer_size.cc',['../flatbuffer__size_8cc.html',1,'']]],
  ['flatbuffer_5fsize_2eh_106',['flatbuffer_size.h',['../flatbuffer__size_8h.html',1,'']]],
  ['flatbuffer_5fsize_2epy_107',['flatbuffer_size.py',['../flatbuffer__size_8py.html',1,'']]],
  ['flatbuffer_5fsize_5fgraph_2epy_108',['flatbuffer_size_graph.py',['../flatbuffer__size__graph_8py.html',1,'']]],
  ['flatbuffer_5fsize_5fgraph_5fhtml_5fconverter_2epy_109',['flatbuffer_size_graph_html_converter.py',['../flatbuffer__size__graph__html__converter_8py.html',1,'']]],
  ['flatbuffer_5fsize_5ftest_2epy_110',['flatbuffer_size_test.py',['../flatbuffer__size__test_8py.html',1,'']]],
  ['flatbuffer_5fsize_5fwrapper_2ecc_111',['flatbuffer_size_wrapper.cc',['../flatbuffer__size__wrapper_8cc.html',1,'']]],
  ['flatbuffer_5fsize_5fwrapper_2eh_112',['flatbuffer_size_wrapper.h',['../flatbuffer__size__wrapper_8h.html',1,'']]],
  ['flatbuffer_5fsize_5fwrapper_5fpybind_2ecc_113',['flatbuffer_size_wrapper_pybind.cc',['../flatbuffer__size__wrapper__pybind_8cc.html',1,'']]],
  ['flatbuffer_5futils_2ecc_114',['flatbuffer_utils.cc',['../flatbuffer__utils_8cc.html',1,'']]],
  ['flatbuffer_5futils_2ecpp_115',['flatbuffer_utils.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src5f1a4c56d39004b3b2c9944f4e5b49aa.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2flatbuffer__utils_8cpp.html',1,'(Global Namespace)']]],
  ['flatbuffer_5futils_2eh_116',['flatbuffer_utils.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcac047de9e9baa03fd549239dd97bdcd9.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2flatbuffer__utils_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2flatbuffer__utils_8h.html',1,'(Global Namespace)']]],
  ['flatbuffer_5futils_2epy_117',['flatbuffer_utils.py',['../flatbuffer__utils_8py.html',1,'']]],
  ['flatbuffer_5futils_5ftest_2ecc_118',['flatbuffer_utils_test.cc',['../flatbuffer__utils__test_8cc.html',1,'']]],
  ['flatbuffer_5futils_5ftest_2epy_119',['flatbuffer_utils_test.py',['../flatbuffer__utils__test_8py.html',1,'']]],
  ['flatbuffers_2eh_120',['flatbuffers.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcd270c8050fc43b4ed99ee8a8df15de22.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2third__party_2flatbuffers_2include_2flatbuffers_2flatbuffers_8h.html',1,'(Global Namespace)']]],
  ['flexbuffers_2eh_121',['flexbuffers.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcfa992099a98c6e0ba9c7aff80f2b2ce2.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2third__party_2flatbuffers_2include_2flatbuffers_2flexbuffers_8h.html',1,'(Global Namespace)']]],
  ['floor_2ecc_122',['floor.cc',['../floor_8cc.html',1,'']]],
  ['floor_2ecpp_123',['floor.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcc674890ed0df5b190f3511b3cc45df2a.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2floor_8cpp.html',1,'(Global Namespace)']]],
  ['floor_2eh_124',['floor.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src614f0fc87b3e542c55d876d1f84322f2.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke5eb643cf8021a770aac1913d5709ce70.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2floor_8h.html',1,'(Global Namespace)']]],
  ['floor_5fdiv_2ecc_125',['floor_div.cc',['../floor__div_8cc.html',1,'']]],
  ['floor_5fdiv_2ecpp_126',['floor_div.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcfe671a36264f38afd3cd3299d00dbb2c.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2floor__div_8cpp.html',1,'(Global Namespace)']]],
  ['floor_5fdiv_2eh_127',['floor_div.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src122567452f4363daae292848a7cb4998.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke54c5e2257e8f5823fef0f8377bb82baa.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2floor__div_8h.html',1,'(Global Namespace)']]],
  ['floor_5fdiv_5ftest_2ecc_128',['floor_div_test.cc',['../floor__div__test_8cc.html',1,'']]],
  ['floor_5fmod_2ecc_129',['floor_mod.cc',['../floor__mod_8cc.html',1,'']]],
  ['floor_5fmod_2ecpp_130',['floor_mod.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcbddc5e30f5e94bf7c1fb08bc390b7b81.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2floor__mod_8cpp.html',1,'(Global Namespace)']]],
  ['floor_5fmod_2eh_131',['floor_mod.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src90a501ef220c6aa1da5747e002e005b5.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke8f433ee71435afe1e0996b5f5af379ba.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2floor__mod_8h.html',1,'(Global Namespace)']]],
  ['floor_5fmod_5ftest_2ecc_132',['floor_mod_test.cc',['../floor__mod__test_8cc.html',1,'']]],
  ['floor_5ftest_2ecc_133',['floor_test.cc',['../floor__test_8cc.html',1,'']]],
  ['foto_2epy_134',['foto.py',['../foto_8py.html',1,'']]],
  ['framer_2ecc_135',['framer.cc',['../framer_8cc.html',1,'']]],
  ['framer_5fflexbuffers_5fgenerated_5fdata_2ecc_136',['framer_flexbuffers_generated_data.cc',['../framer__flexbuffers__generated__data_8cc.html',1,'']]],
  ['framer_5fflexbuffers_5fgenerated_5fdata_2eh_137',['framer_flexbuffers_generated_data.h',['../framer__flexbuffers__generated__data_8h.html',1,'']]],
  ['framer_5fkernel_2ecc_138',['framer_kernel.cc',['../framer__kernel_8cc.html',1,'']]],
  ['framer_5fop_2ecc_139',['framer_op.cc',['../framer__op_8cc.html',1,'']]],
  ['framer_5fop_2epy_140',['framer_op.py',['../framer__op_8py.html',1,'']]],
  ['framer_5fop_5ftest_2epy_141',['framer_op_test.py',['../framer__op__test_8py.html',1,'']]],
  ['framer_5ftest_2ecc_142',['framer_test.cc',['../framer__test_8cc.html',1,'']]],
  ['freq_5fto_5fmel_5ftest_2epy_143',['freq_to_mel_test.py',['../freq__to__mel__test_8py.html',1,'']]],
  ['freq_5fto_5fmel_5fwrapper_2ecc_144',['freq_to_mel_wrapper.cc',['../freq__to__mel__wrapper_8cc.html',1,'']]],
  ['frontend_2ec_145',['frontend.c',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend_8c.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend_8c.html',1,'(Global Namespace)']]],
  ['frontend_2eh_146',['frontend.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend_8h.html',1,'(Global Namespace)']]],
  ['frontend_5fio_2ec_147',['frontend_io.c',['../frontend__io_8c.html',1,'']]],
  ['frontend_5fio_2eh_148',['frontend_io.h',['../frontend__io_8h.html',1,'']]],
  ['frontend_5fmain_2ec_149',['frontend_main.c',['../frontend__main_8c.html',1,'']]],
  ['frontend_5fmemmap_5fgenerator_2ec_150',['frontend_memmap_generator.c',['../frontend__memmap__generator_8c.html',1,'']]],
  ['frontend_5fmemmap_5fmain_2ec_151',['frontend_memmap_main.c',['../frontend__memmap__main_8c.html',1,'']]],
  ['frontend_5ftest_2ecc_152',['frontend_test.cc',['../frontend__test_8cc.html',1,'']]],
  ['frontend_5futil_2ec_153',['frontend_util.c',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend__util_8c.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend__util_8c.html',1,'(Global Namespace)']]],
  ['frontend_5futil_2eh_154',['frontend_util.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend__util_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2frontend__util_8h.html',1,'(Global Namespace)']]],
  ['fully_5fconnected_2ecc_155',['fully_connected.cc',['../tensorflow_2lite_2micro_2kernels_2arc__mli_2fully__connected_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2ceva_2fully__connected_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2cmsis__nn_2fully__connected_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2fully__connected_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2xtensa_2fully__connected_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2xtensa_2hifimini_2fully__connected_8cc.html',1,'(Global Namespace)'],['../third__party_2hexagon_2fully__connected_8cc.html',1,'(Global Namespace)']]],
  ['fully_5fconnected_2ecpp_156',['fully_connected.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcb6422ba4b09c37fea36f264b4bcbc5a2.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2fully__connected_8cpp.html',1,'(Global Namespace)']]],
  ['fully_5fconnected_2eh_157',['fully_connected.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src313e6860468444677b13926d5a21c310.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src0a53b1c4ff975ca702056731c6b31a1e.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src812fe28e6c2694beed735103af8995a1.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke127e3d9fabddbd986b69a8ffa1eb2e2d.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke0da9f9480dabf0e9f106c6d0a78910ae.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mi4d4d17c31cb7c0a3c97487c72609843b.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2fully__connected_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2referen916112f20712eb2daff191b8b06553ef.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2fully__connected_8h.html',1,'(Global Namespace)']]],
  ['fully_5fconnected_2epy_158',['fully_connected.py',['../fully__connected_8py.html',1,'']]],
  ['fully_5fconnected_5fcommon_2ecc_159',['fully_connected_common.cc',['../fully__connected__common_8cc.html',1,'']]],
  ['fully_5fconnected_5fcommon_2ecpp_160',['fully_connected_common.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcb8fce0290958f29c7ccf7c58ddde2990.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2fully__connected__common_8cpp.html',1,'(Global Namespace)']]],
  ['fully_5fconnected_5fcommon_5fxtensa_2ecc_161',['fully_connected_common_xtensa.cc',['../fully__connected__common__xtensa_8cc.html',1,'']]],
  ['fully_5fconnected_5fint8_2ecc_162',['fully_connected_int8.cc',['../tensorflow_2lite_2micro_2kernels_2xtensa_2fully__connected__int8_8cc.html',1,'(Global Namespace)'],['../third__party_2hexagon_2fully__connected__int8_8cc.html',1,'(Global Namespace)']]],
  ['fully_5fconnected_5ftest_2ecc_163',['fully_connected_test.cc',['../fully__connected__test_8cc.html',1,'']]],
  ['fully_5fconnected_5fvision_2ecc_164',['fully_connected_vision.cc',['../fully__connected__vision_8cc.html',1,'']]],
  ['functions_2ehpp_165',['functions.hpp',['../functions_8hpp.html',1,'']]]
];
