var searchData=
[
  ['ehtosu_5fconfig_5fu65_2eh_0',['ehtosu_config_u65.h',['../ehtosu__config__u65_8h.html',1,'']]],
  ['ei_5faligned_5fmalloc_2eh_1',['ei_aligned_malloc.h',['../ei__aligned__malloc_8h.html',1,'']]],
  ['ei_5falignment_2ehpp_2',['ei_alignment.hpp',['../ei__alignment_8hpp.html',1,'']]],
  ['ei_5falloc_2eh_3',['ei_alloc.h',['../ei__alloc_8h.html',1,'']]],
  ['ei_5farm_5fcmsis_5fdsp_2eh_4',['ei_arm_cmsis_dsp.h',['../ei__arm__cmsis__dsp_8h.html',1,'']]],
  ['ei_5fceva_5fdsp_2eh_5',['ei_ceva_dsp.h',['../ei__ceva__dsp_8h.html',1,'']]],
  ['ei_5fclassifier_5fconfig_2eh_6',['ei_classifier_config.h',['../ei__classifier__config_8h.html',1,'']]],
  ['ei_5fclassifier_5fporting_2ecpp_7',['ei_classifier_porting.cpp',['../ambiq_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../arduino_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../clib_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../espressif_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../himax-we2_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../iar_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../infineon-psoc62_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../particle_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)'],['../seeed-vision-ai_2ei__classifier__porting_8cpp.html',1,'(Global Namespace)']]],
  ['ei_5fclassifier_5fporting_2eh_8',['ei_classifier_porting.h',['../ei__classifier__porting_8h.html',1,'']]],
  ['ei_5fclassifier_5fsmooth_2eh_9',['ei_classifier_smooth.h',['../ei__classifier__smooth_8h.html',1,'']]],
  ['ei_5fclassifier_5ftypes_2eh_10',['ei_classifier_types.h',['../ei__classifier__types_8h.html',1,'']]],
  ['ei_5fconstants_2eh_11',['ei_constants.h',['../ei__constants_8h.html',1,'']]],
  ['ei_5fdsp_5fhandle_2eh_12',['ei_dsp_handle.h',['../ei__dsp__handle_8h.html',1,'']]],
  ['ei_5ffill_5fresult_5fstruct_2eh_13',['ei_fill_result_struct.h',['../ei__fill__result__struct_8h.html',1,'']]],
  ['ei_5fflatten_2eh_14',['ei_flatten.h',['../ei__flatten_8h.html',1,'']]],
  ['ei_5fhr_2ehpp_15',['ei_hr.hpp',['../ei__hr_8hpp.html',1,'']]],
  ['ei_5flogging_2eh_16',['ei_logging.h',['../ei__logging_8h.html',1,'']]],
  ['ei_5fmodel_5ftypes_2eh_17',['ei_model_types.h',['../ei__model__types_8h.html',1,'']]],
  ['ei_5fnms_2eh_18',['ei_nms.h',['../ei__nms_8h.html',1,'']]],
  ['ei_5fno_5fhw_5fdsp_2eh_19',['ei_no_hw_dsp.h',['../ei__no__hw__dsp_8h.html',1,'']]],
  ['ei_5fobject_5fcounting_2eh_20',['ei_object_counting.h',['../ei__object__counting_8h.html',1,'']]],
  ['ei_5fobject_5ftracking_2eh_21',['ei_object_tracking.h',['../ei__object__tracking_8h.html',1,'']]],
  ['ei_5fperformance_5fcalibration_2eh_22',['ei_performance_calibration.h',['../ei__performance__calibration_8h.html',1,'']]],
  ['ei_5fpostprocessing_2eh_23',['ei_postprocessing.h',['../ei__postprocessing_8h.html',1,'']]],
  ['ei_5fpostprocessing_5fcommon_2eh_24',['ei_postprocessing_common.h',['../ei__postprocessing__common_8h.html',1,'']]],
  ['ei_5fprofiler_2eh_25',['ei_profiler.h',['../ei__profiler_8h.html',1,'']]],
  ['ei_5fquantize_2eh_26',['ei_quantize.h',['../ei__quantize_8h.html',1,'']]],
  ['ei_5frun_5fclassifier_2eh_27',['ei_run_classifier.h',['../ei__run__classifier_8h.html',1,'']]],
  ['ei_5frun_5fclassifier_5fimage_2eh_28',['ei_run_classifier_image.h',['../ei__run__classifier__image_8h.html',1,'']]],
  ['ei_5frun_5fdsp_2eh_29',['ei_run_dsp.h',['../ei__run__dsp_8h.html',1,'']]],
  ['ei_5fsignal_5fwith_5faxes_2eh_30',['ei_signal_with_axes.h',['../ei__signal__with__axes_8h.html',1,'']]],
  ['ei_5fsignal_5fwith_5frange_2eh_31',['ei_signal_with_range.h',['../ei__signal__with__range_8h.html',1,'']]],
  ['ei_5futils_2eh_32',['ei_utils.h',['../ei__utils_8h.html',1,'']]],
  ['ei_5fvector_2eh_33',['ei_vector.h',['../ei__vector_8h.html',1,'']]],
  ['elementwise_2ecc_34',['elementwise.cc',['../elementwise_8cc.html',1,'']]],
  ['elementwise_2ecpp_35',['elementwise.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srceb17155221795f6c84adc198b18f61e2.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2elementwise_8cpp.html',1,'(Global Namespace)']]],
  ['elementwise_5ftest_2ecc_36',['elementwise_test.cc',['../elementwise__test_8cc.html',1,'']]],
  ['elu_2ecc_37',['elu.cc',['../elu_8cc.html',1,'']]],
  ['elu_2ecpp_38',['elu.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcaa715bcbccfd2c1131fb15ef75f0ddfd.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2elu_8cpp.html',1,'(Global Namespace)']]],
  ['elu_2eh_39',['elu.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src31fc96e620c8985ee309ad9c0d776a82.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke44fc11096e2e91f7cbcfb008b1fa6520.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2elu_8h.html',1,'(Global Namespace)']]],
  ['elu_5ftest_2ecc_40',['elu_test.cc',['../elu__test_8cc.html',1,'']]],
  ['embedding_5flookup_2ecc_41',['embedding_lookup.cc',['../embedding__lookup_8cc.html',1,'']]],
  ['embedding_5flookup_5ftest_2ecc_42',['embedding_lookup_test.cc',['../embedding__lookup__test_8cc.html',1,'']]],
  ['emojibutton_2eino_43',['EmojiButton.ino',['../_emoji_button_8ino.html',1,'']]],
  ['energy_2ecc_44',['energy.cc',['../micro_2kernels_2energy_8cc.html',1,'(Global Namespace)'],['../src_2energy_8cc.html',1,'(Global Namespace)']]],
  ['energy_2eh_45',['energy.h',['../energy_8h.html',1,'']]],
  ['energy_5fflexbuffers_5fgenerated_5fdata_2ecc_46',['energy_flexbuffers_generated_data.cc',['../energy__flexbuffers__generated__data_8cc.html',1,'']]],
  ['energy_5fflexbuffers_5fgenerated_5fdata_2eh_47',['energy_flexbuffers_generated_data.h',['../energy__flexbuffers__generated__data_8h.html',1,'']]],
  ['energy_5fkernel_2ecc_48',['energy_kernel.cc',['../energy__kernel_8cc.html',1,'']]],
  ['energy_5fop_2ecc_49',['energy_op.cc',['../energy__op_8cc.html',1,'']]],
  ['energy_5fop_2epy_50',['energy_op.py',['../energy__op_8py.html',1,'']]],
  ['energy_5fop_5ftest_2epy_51',['energy_op_test.py',['../energy__op__test_8py.html',1,'']]],
  ['energy_5ftest_2ecc_52',['energy_test.cc',['../energy__test_8cc.html',1,'']]],
  ['engines_2eh_53',['engines.h',['../engines_8h.html',1,'']]],
  ['error_5freporter_2ecc_54',['error_reporter.cc',['../error__reporter_8cc.html',1,'']]],
  ['error_5freporter_2ecpp_55',['error_reporter.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcd7a4ad698bb416a867566b88cde836bd.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2core_2api_2error__reporter_8cpp.html',1,'(Global Namespace)']]],
  ['error_5freporter_2eh_56',['error_reporter.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcd60aaa143aa73c8be0325c79fa651ace.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2core_2api_2error__reporter_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2core_2api_2error__reporter_8h.html',1,'(Global Namespace)']]],
  ['esp32_5fcamera_2eino_57',['esp32_camera.ino',['../esp32__camera_8ino.html',1,'']]],
  ['esp32_5ffusion_2eino_58',['esp32_fusion.ino',['../esp32__fusion_8ino.html',1,'']]],
  ['esp32_5fmicrophone_2eino_59',['esp32_microphone.ino',['../esp32__microphone_8ino.html',1,'']]],
  ['esp32_5fmicrophone_5fcontinuous_2eino_60',['esp32_microphone_continuous.ino',['../esp32__microphone__continuous_8ino.html',1,'']]],
  ['esp_5fnn_2eh_61',['esp_nn.h',['../esp__nn_8h.html',1,'']]],
  ['esp_5fnn_5fadd_5fansi_2ec_62',['esp_nn_add_ansi.c',['../esp__nn__add__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fansi_5fc_2eh_63',['esp_nn_ansi_c.h',['../esp__nn__ansi__c_8h.html',1,'']]],
  ['esp_5fnn_5fansi_5fheaders_2eh_64',['esp_nn_ansi_headers.h',['../esp__nn__ansi__headers_8h.html',1,'']]],
  ['esp_5fnn_5favg_5fpool_5fansi_2ec_65',['esp_nn_avg_pool_ansi.c',['../esp__nn__avg__pool__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fconv_5fansi_2ec_66',['esp_nn_conv_ansi.c',['../esp__nn__conv__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fconv_5fesp32p4_2ec_67',['esp_nn_conv_esp32p4.c',['../esp__nn__conv__esp32p4_8c.html',1,'']]],
  ['esp_5fnn_5fconv_5fesp32s3_2ec_68',['esp_nn_conv_esp32s3.c',['../esp__nn__conv__esp32s3_8c.html',1,'']]],
  ['esp_5fnn_5fconv_5fopt_2ec_69',['esp_nn_conv_opt.c',['../esp__nn__conv__opt_8c.html',1,'']]],
  ['esp_5fnn_5fdefs_2eh_70',['esp_nn_defs.h',['../esp__nn__defs_8h.html',1,'']]],
  ['esp_5fnn_5fdepthwise_5fconv_5fansi_2ec_71',['esp_nn_depthwise_conv_ansi.c',['../esp__nn__depthwise__conv__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fdepthwise_5fconv_5fopt_2ec_72',['esp_nn_depthwise_conv_opt.c',['../esp__nn__depthwise__conv__opt_8c.html',1,'']]],
  ['esp_5fnn_5fdepthwise_5fconv_5fs8_5fesp32s3_2ec_73',['esp_nn_depthwise_conv_s8_esp32s3.c',['../esp__nn__depthwise__conv__s8__esp32s3_8c.html',1,'']]],
  ['esp_5fnn_5fesp32p4_2eh_74',['esp_nn_esp32p4.h',['../esp__nn__esp32p4_8h.html',1,'']]],
  ['esp_5fnn_5fesp32s3_2eh_75',['esp_nn_esp32s3.h',['../esp__nn__esp32s3_8h.html',1,'']]],
  ['esp_5fnn_5ffully_5fconnected_5fansi_2ec_76',['esp_nn_fully_connected_ansi.c',['../esp__nn__fully__connected__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fgeneric_5fopt_2eh_77',['esp_nn_generic_opt.h',['../esp__nn__generic__opt_8h.html',1,'']]],
  ['esp_5fnn_5fmax_5fpool_5fansi_2ec_78',['esp_nn_max_pool_ansi.c',['../esp__nn__max__pool__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fmul_5fansi_2ec_79',['esp_nn_mul_ansi.c',['../esp__nn__mul__ansi_8c.html',1,'']]],
  ['esp_5fnn_5frelu_5fansi_2ec_80',['esp_nn_relu_ansi.c',['../esp__nn__relu__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fsoftmax_5fansi_2ec_81',['esp_nn_softmax_ansi.c',['../esp__nn__softmax__ansi_8c.html',1,'']]],
  ['esp_5fnn_5fsoftmax_5fopt_2ec_82',['esp_nn_softmax_opt.c',['../esp__nn__softmax__opt_8c.html',1,'']]],
  ['ethos_5flinux_2eh_83',['ethos_linux.h',['../ethos__linux_8h.html',1,'']]],
  ['ethos_5fu_2einc_84',['ethos_u.inc',['../ethos__u_8inc.html',1,'']]],
  ['ethosu_2ecc_85',['ethosu.cc',['../ethos__u_2ethosu_8cc.html',1,'(Global Namespace)'],['../ethosu_8cc.html',1,'(Global Namespace)']]],
  ['ethosu_2ecpp_86',['ethosu.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcbded45caff273d4ba0671a671cdc54e5.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2ethosu_8cpp.html',1,'(Global Namespace)']]],
  ['ethosu_2eh_87',['ethosu.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src7597fd00c7988d01e65b2ce906099b47.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2ethosu_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2ethosu_8h.html',1,'(Global Namespace)']]],
  ['ethosu55_5finterface_2eh_88',['ethosu55_interface.h',['../ethosu55__interface_8h.html',1,'']]],
  ['ethosu65_5finterface_2eh_89',['ethosu65_interface.h',['../ethosu65__interface_8h.html',1,'']]],
  ['ethosu_5fconfig_5fu55_2eh_90',['ethosu_config_u55.h',['../ethosu__config__u55_8h.html',1,'']]],
  ['ethosu_5fdevice_2eh_91',['ethosu_device.h',['../ethosu__device_8h.html',1,'']]],
  ['ethosu_5fdevice_5fu55_5fu65_2ec_92',['ethosu_device_u55_u65.c',['../ethosu__device__u55__u65_8c.html',1,'']]],
  ['ethosu_5fdriver_2ec_93',['ethosu_driver.c',['../ethos-core-driver_2src_2ethosu__driver_8c.html',1,'(Global Namespace)'],['../himax-we2_2ethosu__driver_8c.html',1,'(Global Namespace)']]],
  ['ethosu_5fdriver_2eh_94',['ethosu_driver.h',['../ethosu__driver_8h.html',1,'']]],
  ['ethosu_5finterface_2eh_95',['ethosu_interface.h',['../ethosu__interface_8h.html',1,'']]],
  ['ethosu_5flog_2eh_96',['ethosu_log.h',['../ethosu__log_8h.html',1,'']]],
  ['ethosu_5fpmu_2ec_97',['ethosu_pmu.c',['../ethosu__pmu_8c.html',1,'']]],
  ['ethosu_5ftypes_2eh_98',['ethosu_types.h',['../ethosu__types_8h.html',1,'']]],
  ['evaluate_2epy_99',['evaluate.py',['../hello__world_2evaluate_8py.html',1,'(Global Namespace)'],['../micro__speech_2evaluate_8py.html',1,'(Global Namespace)'],['../mnist__lstm_2evaluate_8py.html',1,'(Global Namespace)']]],
  ['evaluate_5ftest_2epy_100',['evaluate_test.py',['../hello__world_2evaluate__test_8py.html',1,'(Global Namespace)'],['../micro__speech_2evaluate__test_8py.html',1,'(Global Namespace)'],['../mnist__lstm_2evaluate__test_8py.html',1,'(Global Namespace)']]],
  ['examplealgorithm_2eino_101',['ExampleAlgorithm.ino',['../_example_algorithm_8ino.html',1,'']]],
  ['examplecodesdk_2eino_102',['ExampleCodeSDK.ino',['../_example_code_s_d_k_8ino.html',1,'']]],
  ['examplecodetensorflow_2eino_103',['ExampleCodeTensorFlow.ino',['../_example_code_tensor_flow_8ino.html',1,'']]],
  ['exp_2ecc_104',['exp.cc',['../exp_8cc.html',1,'']]],
  ['exp_2ecpp_105',['exp.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src0e53dea9a9048158963d561d85314991.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2exp_8cpp.html',1,'(Global Namespace)']]],
  ['exp_2eh_106',['exp.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src2d58b8594bee8be88b73d3f924f00ac8.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke67a547220d5952bfae6e04d2b491b377.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2exp_8h.html',1,'(Global Namespace)']]],
  ['exp_5ftest_2ecc_107',['exp_test.cc',['../exp__test_8cc.html',1,'']]],
  ['expand_5fdims_2ecc_108',['expand_dims.cc',['../expand__dims_8cc.html',1,'']]],
  ['expand_5fdims_2ecpp_109',['expand_dims.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src7cd9d893280504f54344bb1b481ec340.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2expand__dims_8cpp.html',1,'(Global Namespace)']]],
  ['expand_5fdims_5ftest_2ecc_110',['expand_dims_test.cc',['../expand__dims__test_8cc.html',1,'']]],
  ['expand_5fstamp_5fvars_2epy_111',['expand_stamp_vars.py',['../expand__stamp__vars_8py.html',1,'']]],
  ['expand_5fstamp_5fvars_5ftest_2epy_112',['expand_stamp_vars_test.py',['../expand__stamp__vars__test_8py.html',1,'']]],
  ['eyalroz_5fprintf_2einc_113',['eyalroz_printf.inc',['../eyalroz__printf_8inc.html',1,'']]]
];
