var searchData=
[
  ['saveimage_2eino_0',['SaveImage.ino',['../_save_image_8ino.html',1,'']]],
  ['scatter_5fnd_2ecpp_1',['scatter_nd.cpp',['../scatter__nd_8cpp.html',1,'']]],
  ['scatter_5fnd_2eh_2',['scatter_nd.h',['../scatter__nd_8h.html',1,'']]],
  ['schema_5fgenerated_2eh_3',['schema_generated.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src1ec2831d753f9cd0fb9517c595c678db.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2schema_2schema__generated_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2schema_2schema__generated_8h.html',1,'(Global Namespace)']]],
  ['schema_5fgenerated_5ffull_2eh_4',['schema_generated_full.h',['../schema__generated__full_8h.html',1,'']]],
  ['schema_5fpy_5fgenerated_2epy_5',['schema_py_generated.py',['../schema__py__generated_8py.html',1,'']]],
  ['schema_5futil_2epy_6',['schema_util.py',['../schema__util_8py.html',1,'']]],
  ['schema_5futils_2ecc_7',['schema_utils.cc',['../schema__utils_8cc.html',1,'']]],
  ['schema_5futils_2ecpp_8',['schema_utils.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src4768a7db00b1fa883230605e05a86a04.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2schema__utils_8cpp.html',1,'(Global Namespace)']]],
  ['schema_5futils_2eh_9',['schema_utils.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src405a251998aef13df3476161b7df4082.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2schema_2schema__utils_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2schema_2schema__utils_8h.html',1,'(Global Namespace)']]],
  ['scratch_5fbuf_5fmgr_2ecc_10',['scratch_buf_mgr.cc',['../scratch__buf__mgr_8cc.html',1,'']]],
  ['scratch_5fbuf_5fmgr_2ecpp_11',['scratch_buf_mgr.cpp',['../scratch__buf__mgr_8cpp.html',1,'']]],
  ['scratch_5fbuf_5fmgr_2eh_12',['scratch_buf_mgr.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mifeda4d875370bafe569885bd23dfd6bb.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2scratch__buf__mgr_8h.html',1,'(Global Namespace)']]],
  ['scratch_5fbuffers_2ecc_13',['scratch_buffers.cc',['../scratch__buffers_8cc.html',1,'']]],
  ['scratch_5fbuffers_2ecpp_14',['scratch_buffers.cpp',['../scratch__buffers_8cpp.html',1,'']]],
  ['scratch_5fbuffers_2eh_15',['scratch_buffers.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mi8988c79dc9caf60250ddf649f0b3f1c3.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2scratch__buffers_8h.html',1,'(Global Namespace)']]],
  ['security_2emd_16',['SECURITY.md',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2_s_e_c_u_r_i_t_y_8md.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2porting_2ethos-core-driver_2_s_e_c_u_r_i_t_y_8md.html',1,'(Global Namespace)']]],
  ['select_2ecc_17',['select.cc',['../select_8cc.html',1,'']]],
  ['select_2ecpp_18',['select.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcb6b679fa302420de67f72c8d32a88f02.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2select_8cpp.html',1,'(Global Namespace)']]],
  ['select_2eh_19',['select.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src9375f723d58c5d310c62c3b950daf4c6.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kea0836887c0791a5d9eb1e711d93d4e37.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2select_8h.html',1,'(Global Namespace)']]],
  ['select_5ftest_2ecc_20',['select_test.cc',['../select__test_8cc.html',1,'']]],
  ['shape_2ecc_21',['shape.cc',['../shape_8cc.html',1,'']]],
  ['shape_2ecpp_22',['shape.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src47ab3a10ef199e8ad511b1c9a952032e.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2shape_8cpp.html',1,'(Global Namespace)']]],
  ['shape_5ftest_2ecc_23',['shape_test.cc',['../shape__test_8cc.html',1,'']]],
  ['shared_5flibrary_2eh_24',['shared_library.h',['../shared__library_8h.html',1,'']]],
  ['signal_2ehpp_25',['signal.hpp',['../signal_8hpp.html',1,'']]],
  ['simplecamera_2epy_26',['SimpleCamera.py',['../_simple_camera_8py.html',1,'']]],
  ['simplemodel_2epy_27',['SimpleModel.py',['../_simple_model_8py.html',1,'']]],
  ['simpletemperature_2eino_28',['SimpleTemperature.ino',['../_simple_temperature_8ino.html',1,'']]],
  ['simplewebserver_2eino_29',['SimpleWebServer.ino',['../_simple_web_server_8ino.html',1,'']]],
  ['sinewaveled_2eino_30',['SineWaveLED.ino',['../_sine_wave_l_e_d_8ino.html',1,'']]],
  ['single_5farena_5fbuffer_5fallocator_2ecc_31',['single_arena_buffer_allocator.cc',['../single__arena__buffer__allocator_8cc.html',1,'']]],
  ['single_5farena_5fbuffer_5fallocator_2ecpp_32',['single_arena_buffer_allocator.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src84be0e60d13b8bf4db0543950040de8b.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2single__arena__buffer__allocator_8cpp.html',1,'(Global Namespace)']]],
  ['single_5farena_5fbuffer_5fallocator_2eh_33',['single_arena_buffer_allocator.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src208a988b7cdd4a63346221938102f0e9.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2miaf38ae94856a81d4da9555770b3f4ffd.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2single__arena__buffer__allocator_8h.html',1,'(Global Namespace)']]],
  ['single_5farena_5fbuffer_5fallocator_5ftest_2ecc_34',['single_arena_buffer_allocator_test.cc',['../single__arena__buffer__allocator__test_8cc.html',1,'']]],
  ['size_5fcomp_2epy_35',['size_comp.py',['../size__comp_8py.html',1,'']]],
  ['slice_2ecc_36',['slice.cc',['../slice_8cc.html',1,'']]],
  ['slice_2ecpp_37',['slice.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src7770106a036efda3e347266dc433d458.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2slice_8cpp.html',1,'(Global Namespace)']]],
  ['slice_2eh_38',['slice.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcac85b01ee305f2f4cb3ef599929e1cf4.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2keb3fd3f9c357af4e1e4ef6bbe8d9c649b.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2slice_8h.html',1,'(Global Namespace)']]],
  ['slice_5ftest_2ecc_39',['slice_test.cc',['../slice__test_8cc.html',1,'']]],
  ['softmax_2ecc_40',['softmax.cc',['../ceva_2softmax_8cc.html',1,'(Global Namespace)'],['../cmsis__nn_2softmax_8cc.html',1,'(Global Namespace)'],['../softmax_8cc.html',1,'(Global Namespace)'],['../xtensa_2softmax_8cc.html',1,'(Global Namespace)']]],
  ['softmax_2ecpp_41',['softmax.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src293418c7134b4d249a55ca6a4f3a74b8.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2softmax_8cpp.html',1,'(Global Namespace)']]],
  ['softmax_2eh_42',['softmax.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src1ba051633ba42c64c7cf89d31cf83bd4.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src76bc54f7a0ef0e2f35cc683387caa037.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kec2b1f1282f92ad67c0a77f2e7934a2b2.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2softmax_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2softmax_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2softmax_8h.html',1,'(Global Namespace)']]],
  ['softmax_5fcommon_2ecc_43',['softmax_common.cc',['../softmax__common_8cc.html',1,'']]],
  ['softmax_5fcommon_2ecpp_44',['softmax_common.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src0852067cc174444a13d498437c3973ce.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2softmax__common_8cpp.html',1,'(Global Namespace)']]],
  ['softmax_5fcommon_2eh_45',['softmax_common.h',['../softmax__common_8h.html',1,'']]],
  ['softmax_5fint8_5fint16_2ecc_46',['softmax_int8_int16.cc',['../softmax__int8__int16_8cc.html',1,'']]],
  ['softmax_5ftest_2ecc_47',['softmax_test.cc',['../softmax__test_8cc.html',1,'']]],
  ['softmax_5fvision_2ecc_48',['softmax_vision.cc',['../softmax__vision_8cc.html',1,'']]],
  ['sony_5fspresense_5fcamera_2eino_49',['sony_spresense_camera.ino',['../sony__spresense__camera_8ino.html',1,'']]],
  ['sony_5fspresense_5fmicrophone_2eino_50',['sony_spresense_microphone.ino',['../sony__spresense__microphone_8ino.html',1,'']]],
  ['sony_5fspresense_5fmicrophone_5fcontinuous_2eino_51',['sony_spresense_microphone_continuous.ino',['../sony__spresense__microphone__continuous_8ino.html',1,'']]],
  ['space_5fto_5fbatch_5fnd_2ecc_52',['space_to_batch_nd.cc',['../space__to__batch__nd_8cc.html',1,'']]],
  ['space_5fto_5fbatch_5fnd_2ecpp_53',['space_to_batch_nd.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src75126934fb71c2af2a5dc823fcf30ef8.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2space__to__batch__nd_8cpp.html',1,'(Global Namespace)']]],
  ['space_5fto_5fbatch_5fnd_2eh_54',['space_to_batch_nd.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src6905dfb1350fa25b334643bb302064bf.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke88659e2de197caec5f5db9712c4c57b8.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2space__to__batch__nd_8h.html',1,'(Global Namespace)']]],
  ['space_5fto_5fbatch_5fnd_5ftest_2ecc_55',['space_to_batch_nd_test.cc',['../space__to__batch__nd__test_8cc.html',1,'']]],
  ['space_5fto_5fdepth_2ecc_56',['space_to_depth.cc',['../space__to__depth_8cc.html',1,'']]],
  ['space_5fto_5fdepth_2ecpp_57',['space_to_depth.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src349f5bb0c3b7723aa4a2af3d165933cd.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2space__to__depth_8cpp.html',1,'(Global Namespace)']]],
  ['space_5fto_5fdepth_2eh_58',['space_to_depth.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src67f82ce370459b4577397fadb799c4b5.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kedfa7e0d62c110b484d1c046e1026f07f.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2space__to__depth_8h.html',1,'(Global Namespace)']]],
  ['space_5fto_5fdepth_5ftest_2ecc_59',['space_to_depth_test.cc',['../space__to__depth__test_8cc.html',1,'']]],
  ['specialize_5ffiles_2epy_60',['specialize_files.py',['../specialize__files_8py.html',1,'']]],
  ['spectral_2ehpp_61',['spectral.hpp',['../spectral_8hpp.html',1,'']]],
  ['speechpy_2ehpp_62',['speechpy.hpp',['../speechpy_8hpp.html',1,'']]],
  ['split_2ecc_63',['split.cc',['../split_8cc.html',1,'']]],
  ['split_2ecpp_64',['split.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srccfffb220fe7190844298febf826b26d2.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2split_8cpp.html',1,'(Global Namespace)']]],
  ['split_5ftest_2ecc_65',['split_test.cc',['../split__test_8cc.html',1,'']]],
  ['split_5fv_2ecc_66',['split_v.cc',['../split__v_8cc.html',1,'']]],
  ['split_5fv_2ecpp_67',['split_v.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srccc765b3b283094af02a81561629a6986.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2split__v_8cpp.html',1,'(Global Namespace)']]],
  ['split_5fv_5ftest_2ecc_68',['split_v_test.cc',['../split__v__test_8cc.html',1,'']]],
  ['square_5froot_2eh_69',['square_root.h',['../square__root_8h.html',1,'']]],
  ['square_5froot_5f32_2ecc_70',['square_root_32.cc',['../square__root__32_8cc.html',1,'']]],
  ['square_5froot_5f64_2ecc_71',['square_root_64.cc',['../square__root__64_8cc.html',1,'']]],
  ['squared_5fdifference_2ecc_72',['squared_difference.cc',['../squared__difference_8cc.html',1,'']]],
  ['squared_5fdifference_2ecpp_73',['squared_difference.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src365627f8c8f2b1728a26332c0f9490e4.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2squared__difference_8cpp.html',1,'(Global Namespace)']]],
  ['squared_5fdifference_5ftest_2ecc_74',['squared_difference_test.cc',['../squared__difference__test_8cc.html',1,'']]],
  ['squeeze_2ecc_75',['squeeze.cc',['../squeeze_8cc.html',1,'']]],
  ['squeeze_2ecpp_76',['squeeze.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src5afb18c45f6346167aa977a363205143.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2squeeze_8cpp.html',1,'(Global Namespace)']]],
  ['squeeze_5ftest_2ecc_77',['squeeze_test.cc',['../squeeze__test_8cc.html',1,'']]],
  ['stacker_2ecc_78',['stacker.cc',['../stacker_8cc.html',1,'']]],
  ['stacker_5fflexbuffers_5fgenerated_5fdata_2ecc_79',['stacker_flexbuffers_generated_data.cc',['../stacker__flexbuffers__generated__data_8cc.html',1,'']]],
  ['stacker_5fflexbuffers_5fgenerated_5fdata_2eh_80',['stacker_flexbuffers_generated_data.h',['../stacker__flexbuffers__generated__data_8h.html',1,'']]],
  ['stacker_5fkernel_2ecc_81',['stacker_kernel.cc',['../stacker__kernel_8cc.html',1,'']]],
  ['stacker_5fop_2ecc_82',['stacker_op.cc',['../stacker__op_8cc.html',1,'']]],
  ['stacker_5fop_2epy_83',['stacker_op.py',['../stacker__op_8py.html',1,'']]],
  ['stacker_5fop_5ftest_2epy_84',['stacker_op_test.py',['../stacker__op__test_8py.html',1,'']]],
  ['stacker_5ftest_2ecc_85',['stacker_test.cc',['../stacker__test_8cc.html',1,'']]],
  ['static_5fbuffer_2eino_86',['static_buffer.ino',['../static__buffer_8ino.html',1,'']]],
  ['statistics_5ffunctions_2eh_87',['statistics_functions.h',['../statistics__functions_8h.html',1,'']]],
  ['statistics_5ffunctions_5ff16_2eh_88',['statistics_functions_f16.h',['../statistics__functions__f16_8h.html',1,'']]],
  ['stl_5femulation_2eh_89',['stl_emulation.h',['../stl__emulation_8h.html',1,'']]],
  ['strided_5fslice_2ecc_90',['strided_slice.cc',['../strided__slice_8cc.html',1,'(Global Namespace)'],['../xtensa_2strided__slice_8cc.html',1,'(Global Namespace)']]],
  ['strided_5fslice_2ecpp_91',['strided_slice.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcdc91c794b43404000e39f72876c1c287.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2strided__slice_8cpp.html',1,'(Global Namespace)']]],
  ['strided_5fslice_2eh_92',['strided_slice.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src043a9355f960ed19e55e89220b0f2080.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2keb61b2159e554fa8d4cccf9c2c3391937.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2strided__slice_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2strided__slice_8h.html',1,'(Global Namespace)']]],
  ['strided_5fslice_5fcommon_2ecc_93',['strided_slice_common.cc',['../strided__slice__common_8cc.html',1,'']]],
  ['strided_5fslice_5flogic_2eh_94',['strided_slice_logic.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcf73e8de8b60f3f8f6a6c32deb5d9cd58.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke7e8a53eab5e30c02d133f999af164e6a.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2strided__slice__logic_8h.html',1,'(Global Namespace)']]],
  ['strided_5fslice_5ftest_2ecc_95',['strided_slice_test.cc',['../strided__slice__test_8cc.html',1,'']]],
  ['string_2eh_96',['string.h',['../string_8h.html',1,'']]],
  ['strip_5fstrings_2epy_97',['strip_strings.py',['../strip__strings_8py.html',1,'']]],
  ['struct_2eh_98',['struct.h',['../struct_8h.html',1,'']]],
  ['sub_2ecc_99',['sub.cc',['../sub_8cc.html',1,'(Global Namespace)'],['../xtensa_2sub_8cc.html',1,'(Global Namespace)']]],
  ['sub_2ecpp_100',['sub.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src7228b38b3c07f8e53ad34425226cbd50.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2sub_8cpp.html',1,'(Global Namespace)']]],
  ['sub_2eh_101',['sub.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src5e8489f8880743cdf8581a324c5f6c9b.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src69ffe7e2002aaf4761e49be4691af2e6.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kec454bee6fefe0f3bd9b0f874d9eba225.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2sub_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2sub_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2sub_8h.html',1,'(Global Namespace)']]],
  ['sub_5fcommon_2ecc_102',['sub_common.cc',['../sub__common_8cc.html',1,'']]],
  ['sub_5fcommon_2ecpp_103',['sub_common.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcb721b529b6f44fa7ebc3a0bcefcafd87.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2sub__common_8cpp.html',1,'(Global Namespace)']]],
  ['sub_5ftest_2ecc_104',['sub_test.cc',['../sub__test_8cc.html',1,'']]],
  ['support_5ffunctions_2eh_105',['support_functions.h',['../support__functions_8h.html',1,'']]],
  ['support_5ffunctions_5ff16_2eh_106',['support_functions_f16.h',['../support__functions__f16_8h.html',1,'']]],
  ['svdf_2ecc_107',['svdf.cc',['../tensorflow_2lite_2micro_2kernels_2cmsis__nn_2svdf_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2svdf_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2xtensa_2hifimini_2svdf_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2micro_2kernels_2xtensa_2svdf_8cc.html',1,'(Global Namespace)'],['../third__party_2hexagon_2svdf_8cc.html',1,'(Global Namespace)']]],
  ['svdf_2ecpp_108',['svdf.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcf30ef60d21adebafa776b29e19fb2fe6.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2svdf_8cpp.html',1,'(Global Namespace)']]],
  ['svdf_2eh_109',['svdf.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src0add6c96785e3c5c482b4ffcca072eab.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2svdf_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2svdf_8h.html',1,'(Global Namespace)']]],
  ['svdf_5fcommon_2ecc_110',['svdf_common.cc',['../svdf__common_8cc.html',1,'']]],
  ['svdf_5fcommon_2ecpp_111',['svdf_common.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcf68eadf68059c5e3f9136c1727502f8c.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2svdf__common_8cpp.html',1,'(Global Namespace)']]],
  ['svdf_5fint8_2ecc_112',['svdf_int8.cc',['../svdf__int8_8cc.html',1,'']]],
  ['svdf_5ftest_2ecc_113',['svdf_test.cc',['../svdf__test_8cc.html',1,'']]],
  ['svm_5fdefines_2eh_114',['svm_defines.h',['../svm__defines_8h.html',1,'']]],
  ['svm_5ffunctions_2eh_115',['svm_functions.h',['../svm__functions_8h.html',1,'']]],
  ['svm_5ffunctions_5ff16_2eh_116',['svm_functions_f16.h',['../svm__functions__f16_8h.html',1,'']]],
  ['system_5fsetup_2ecc_117',['system_setup.cc',['../arc__custom_2system__setup_8cc.html',1,'(Global Namespace)'],['../ceva_2system__setup_8cc.html',1,'(Global Namespace)'],['../cortex__m__corstone__300_2system__setup_8cc.html',1,'(Global Namespace)'],['../hexagon_2system__setup_8cc.html',1,'(Global Namespace)'],['../system__setup_8cc.html',1,'(Global Namespace)']]],
  ['system_5fsetup_2ecpp_118',['system_setup.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcd5c723f08a4a182da6f74a2f94b88291.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2system__setup_8cpp.html',1,'(Global Namespace)']]],
  ['system_5fsetup_2eh_119',['system_setup.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcc6057fbf9e22fede9eba3cd8b1c43354.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2system__setup_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2system__setup_8h.html',1,'(Global Namespace)']]]
];
