var searchData=
[
  ['qemu_2emd_0',['qemu.md',['../qemu_8md.html',1,'']]],
  ['quantization_5futil_2ecc_1',['quantization_util.cc',['../quantization__util_8cc.html',1,'']]],
  ['quantization_5futil_2ecpp_2',['quantization_util.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcb3a042f4d9c6adcc4984977539ac1209.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2quantization__util_8cpp.html',1,'(Global Namespace)']]],
  ['quantization_5futil_2eh_3',['quantization_util.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src86d720b1cf2e09e283af6486a8a32867.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke9f1a2879c2b4e1a95feb12aa4b0ed039.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2quantization__util_8h.html',1,'(Global Namespace)']]],
  ['quantization_5futil_5ftest_2ecc_4',['quantization_util_test.cc',['../quantization__util__test_8cc.html',1,'']]],
  ['quantize_2ecc_5',['quantize.cc',['../ceva_2quantize_8cc.html',1,'(Global Namespace)'],['../quantize_8cc.html',1,'(Global Namespace)'],['../xtensa_2quantize_8cc.html',1,'(Global Namespace)']]],
  ['quantize_2ecpp_6',['quantize.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcfc00c55d646e7df386e607e4b8e17a7c.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2quantize_8cpp.html',1,'(Global Namespace)']]],
  ['quantize_2eh_7',['quantize.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src8d88dfd20523ef274903de5a2740912e.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src9bf5dab080d144dcc1bc6b1e45315fde.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke2194aa54280ea5c55e3d02814a2208f2.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2quantize_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2quantize_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2quantize_8h.html',1,'(Global Namespace)']]],
  ['quantize_5fcommon_2ecc_8',['quantize_common.cc',['../quantize__common_8cc.html',1,'']]],
  ['quantize_5fcommon_2ecpp_9',['quantize_common.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srce1baad886fbdc67ad584150e4ec6d29a.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2quantize__common_8cpp.html',1,'(Global Namespace)']]],
  ['quantize_5ftest_2ecc_10',['quantize_test.cc',['../quantize__test_8cc.html',1,'']]],
  ['quaternion_5fmath_5ffunctions_2eh_11',['quaternion_math_functions.h',['../quaternion__math__functions_8h.html',1,'']]]
];
