var searchData=
[
  ['kalmanfilter_2eino_0',['KalmanFilter.ino',['../_kalman_filter_8ino.html',1,'']]],
  ['kernel_5frunner_2ecc_1',['kernel_runner.cc',['../kernel__runner_8cc.html',1,'']]],
  ['kernel_5frunner_2ecpp_2',['kernel_runner.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcc6edae44a08327b21b0956c3b863e97c.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2kernel__runner_8cpp.html',1,'(Global Namespace)']]],
  ['kernel_5frunner_2eh_3',['kernel_runner.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srce4d36522f95333dd92bb9bc111588385.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2kernel__runner_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2kernel__runner_8h.html',1,'(Global Namespace)']]],
  ['kernel_5futil_2ecc_4',['kernel_util.cc',['../kernels_2kernel__util_8cc.html',1,'(Global Namespace)'],['../micro_2kernels_2kernel__util_8cc.html',1,'(Global Namespace)']]],
  ['kernel_5futil_2ecpp_5',['kernel_util.cpp',['../kernels_2kernel__util_8cpp.html',1,'(Global Namespace)'],['../micro_2kernels_2kernel__util_8cpp.html',1,'(Global Namespace)']]],
  ['kernel_5futil_2eh_6',['kernel_util.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcf15325f4f92b30946c468f1a8898c995.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src750414308ff5e73a34261fea375b794f.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kernels_2kernel__util_8h.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2kernel__util_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2kernel__util_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2kernel__util_8h.html',1,'(Global Namespace)']]],
  ['kernel_5futil_5flite_2ecpp_7',['kernel_util_lite.cpp',['../kernel__util__lite_8cpp.html',1,'']]],
  ['kernel_5futil_5fmicro_2ecpp_8',['kernel_util_micro.cpp',['../kernel__util__micro_8cpp.html',1,'']]],
  ['keyword_5fbenchmark_2ecc_9',['keyword_benchmark.cc',['../keyword__benchmark_8cc.html',1,'']]],
  ['keyword_5fbenchmark_5f8bit_2ecc_10',['keyword_benchmark_8bit.cc',['../keyword__benchmark__8bit_8cc.html',1,'']]],
  ['kiss_5ffft_2ec_11',['kiss_fft.c',['../kiss__fft_8c.html',1,'']]],
  ['kiss_5ffft_2ecpp_12',['kiss_fft.cpp',['../kiss__fft_8cpp.html',1,'']]],
  ['kiss_5ffft_2eh_13',['kiss_fft.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcd60fd2c96e0a236dfb5f77629fb99d4f.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2dsp_2kissfft_2kiss__fft_8h.html',1,'(Global Namespace)']]],
  ['kiss_5ffft_5fcommon_2eh_14',['kiss_fft_common.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2kiss__fft__common_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2signal_2src_2kiss__fft__wrappers_2kiss__fft__common_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2kiss__fft__common_8h.html',1,'(Global Namespace)']]],
  ['kiss_5ffft_5ffloat_2ecc_15',['kiss_fft_float.cc',['../kiss__fft__float_8cc.html',1,'']]],
  ['kiss_5ffft_5ffloat_2eh_16',['kiss_fft_float.h',['../kiss__fft__float_8h.html',1,'']]],
  ['kiss_5ffft_5fint16_2ecc_17',['kiss_fft_int16.cc',['../signal_2src_2kiss__fft__wrappers_2kiss__fft__int16_8cc.html',1,'(Global Namespace)'],['../tensorflow_2lite_2experimental_2microfrontend_2lib_2kiss__fft__int16_8cc.html',1,'(Global Namespace)']]],
  ['kiss_5ffft_5fint16_2ecpp_18',['kiss_fft_int16.cpp',['../kiss__fft__int16_8cpp.html',1,'']]],
  ['kiss_5ffft_5fint16_2eh_19',['kiss_fft_int16.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2kiss__fft__int16_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2signal_2src_2kiss__fft__wrappers_2kiss__fft__int16_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2kiss__fft__int16_8h.html',1,'(Global Namespace)']]],
  ['kiss_5ffft_5fint32_2ecc_20',['kiss_fft_int32.cc',['../kiss__fft__int32_8cc.html',1,'']]],
  ['kiss_5ffft_5fint32_2eh_21',['kiss_fft_int32.h',['../kiss__fft__int32_8h.html',1,'']]],
  ['kiss_5ffftr_2ec_22',['kiss_fftr.c',['../kiss__fftr_8c.html',1,'']]],
  ['kiss_5ffftr_2ecpp_23',['kiss_fftr.cpp',['../kiss__fftr_8cpp.html',1,'']]],
  ['kiss_5ffftr_2eh_24',['kiss_fftr.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src18be51f66e984310a95bab7aac63d060.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2dsp_2kissfft_2kiss__fftr_8h.html',1,'(Global Namespace)']]],
  ['kissfft_2eh_25',['kissfft.h',['../kissfft_8h.html',1,'']]],
  ['konvertierung_2epy_26',['Konvertierung.py',['../_konvertierung_8py.html',1,'']]],
  ['konvertierung_5fopt_2epy_27',['Konvertierung_Opt.py',['../_konvertierung___opt_8py.html',1,'']]]
];
