var searchData=
[
  ['barcode_2epy_0',['BarCode.py',['../_bar_code_8py.html',1,'']]],
  ['base_2eh_1',['base.h',['../base_8h.html',1,'']]],
  ['base64_2ecpp_2',['base64.cpp',['../base64_8cpp.html',1,'']]],
  ['base64_2eh_3',['base64.h',['../base64_8h.html',1,'']]],
  ['baseline_5fmemory_5ffootprint_2ecc_4',['baseline_memory_footprint.cc',['../baseline__memory__footprint_8cc.html',1,'']]],
  ['basic_5fmath_5ffunctions_2eh_5',['basic_math_functions.h',['../basic__math__functions_8h.html',1,'']]],
  ['basic_5fmath_5ffunctions_5ff16_2eh_6',['basic_math_functions_f16.h',['../basic__math__functions__f16_8h.html',1,'']]],
  ['batch_5fmatmul_2ecc_7',['batch_matmul.cc',['../batch__matmul_8cc.html',1,'']]],
  ['batch_5fmatmul_2ecpp_8',['batch_matmul.cpp',['../batch__matmul_8cpp.html',1,'']]],
  ['batch_5fmatmul_2eh_9',['batch_matmul.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src8dcdb0948d5cdedbc5c26ff9a2aa314f.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke006095951938d7185577f9e82cab7f50.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2batch__matmul_8h.html',1,'(Global Namespace)']]],
  ['batch_5fmatmul_5ftest_2ecc_10',['batch_matmul_test.cc',['../batch__matmul__test_8cc.html',1,'']]],
  ['batch_5fto_5fspace_5fnd_2ecc_11',['batch_to_space_nd.cc',['../batch__to__space__nd_8cc.html',1,'']]],
  ['batch_5fto_5fspace_5fnd_2ecpp_12',['batch_to_space_nd.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcbff0134e66cadf240bb261d81320d030.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2batch__to__space__nd_8cpp.html',1,'(Global Namespace)']]],
  ['batch_5fto_5fspace_5fnd_2eh_13',['batch_to_space_nd.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srce5e5960299d864f8c29fcb9737ca0e50.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kebcd354cbe52c8ed5607eacc91c01972a.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2batch__to__space__nd_8h.html',1,'(Global Namespace)']]],
  ['batch_5fto_5fspace_5fnd_5ftest_2ecc_14',['batch_to_space_nd_test.cc',['../batch__to__space__nd__test_8cc.html',1,'']]],
  ['bayes_5ffunctions_2eh_15',['bayes_functions.h',['../bayes__functions_8h.html',1,'']]],
  ['bayes_5ffunctions_5ff16_2eh_16',['bayes_functions_f16.h',['../bayes__functions__f16_8h.html',1,'']]],
  ['binary_5ffunction_2eh_17',['binary_function.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src3a791ac76a757ffd42e16fd5a325211a.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2keb1f3c58f67d7f4e68dfa4ddae4b34cf4.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2binary__function_8h.html',1,'(Global Namespace)']]],
  ['binary_5fsize_5ftest_2ecc_18',['binary_size_test.cc',['../binary__size__test_8cc.html',1,'']]],
  ['bits_2eh_19',['bits.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2bits_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2bits_8h.html',1,'(Global Namespace)']]],
  ['blink_2eino_20',['BLINK.ino',['../_arduino_c_l_i_2_b_l_i_n_k_8ino.html',1,'']]],
  ['blink_2eino_21',['Blink.ino',['../_blink_2_b_l_i_n_k_8ino.html',1,'']]],
  ['blink_2epy_22',['Blink.py',['../_blink_8py.html',1,'']]],
  ['blinkdualcore_2eino_23',['BlinkDualCore.ino',['../_blink_dual_core_8ino.html',1,'']]],
  ['blinknicla_2eino_24',['BlinkNicla.ino',['../_blink_nicla_8ino.html',1,'']]],
  ['blob_2epy_25',['Blob.py',['../_blob_8py.html',1,'']]],
  ['bluepill_5fmakefile_2einc_26',['bluepill_makefile.inc',['../bluepill__makefile_8inc.html',1,'']]],
  ['bluetooth_2eino_27',['bluetooth.ino',['../bluetooth_8ino.html',1,'']]],
  ['broadcast_5fargs_2ecc_28',['broadcast_args.cc',['../broadcast__args_8cc.html',1,'']]],
  ['broadcast_5fargs_2ecpp_29',['broadcast_args.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src4f26b71a57450046cc006a62d6ae15ac.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2broadcast__args_8cpp.html',1,'(Global Namespace)']]],
  ['broadcast_5fargs_2eh_30',['broadcast_args.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src64f996886525228de9d11f91d444d0a8.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2keab3439db9da5732f5fcc9a3258e835e0.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2broadcast__args_8h.html',1,'(Global Namespace)']]],
  ['broadcast_5fargs_5ftest_2ecc_31',['broadcast_args_test.cc',['../broadcast__args__test_8cc.html',1,'']]],
  ['broadcast_5fto_2ecc_32',['broadcast_to.cc',['../broadcast__to_8cc.html',1,'']]],
  ['broadcast_5fto_2ecpp_33',['broadcast_to.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcac8b7f6228afd87a4273e82c3f06c42c.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2broadcast__to_8cpp.html',1,'(Global Namespace)']]],
  ['broadcast_5fto_2eh_34',['broadcast_to.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src21a532f98d7b4191198d6ae8dfd3e72a.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2keac70495ff9c9d73dc05846c16065747b.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2broadcast__to_8h.html',1,'(Global Namespace)']]],
  ['broadcast_5fto_5ftest_2ecc_35',['broadcast_to_test.cc',['../broadcast__to__test_8cc.html',1,'']]],
  ['buffer_2eh_36',['buffer.h',['../buffer_8h.html',1,'']]],
  ['buffer_5fref_2eh_37',['buffer_ref.h',['../buffer__ref_8h.html',1,'']]],
  ['build_2epy_38',['BUILD.py',['../_b_u_i_l_d_8py.html',1,'']]],
  ['builtin_5fop_5fdata_2eh_39',['builtin_op_data.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srccda6cdd686aaeac2c9cb10d959ffdcb3.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcf24a30b755d293c76ec2a74f629a4f00.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src7f67a4373e2a0d20daf1d1ff4e1f4339.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2builtin__op__data_8h.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2c_2builtin__op__data_8h.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2core_2c_2builtin__op__data_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2builtin__op__data_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2c_2builtin__op__data_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2core_2c_2builtin__op__data_8h.html',1,'(Global Namespace)']]],
  ['builtin_5fops_2eh_40',['builtin_ops.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src1936c9cb93b395cee9082ccf5816d8b5.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2builtin__ops_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2builtin__ops_8h.html',1,'(Global Namespace)']]],
  ['button_2eh_41',['button.h',['../button_8h.html',1,'']]],
  ['button_5farduino_2ecpp_42',['button_arduino.cpp',['../button__arduino_8cpp.html',1,'']]]
];
