var searchData=
[
  ['nano_5fble33_5fsense_5faccelerometer_2eino_0',['nano_ble33_sense_accelerometer.ino',['../nano__ble33__sense__accelerometer_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5faccelerometer_5fcontinuous_2eino_1',['nano_ble33_sense_accelerometer_continuous.ino',['../nano__ble33__sense__accelerometer__continuous_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5fcamera_2eino_2',['nano_ble33_sense_camera.ino',['../nano__ble33__sense__camera_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5ffusion_2eino_3',['nano_ble33_sense_fusion.ino',['../nano__ble33__sense__fusion_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5fmicrophone_2eino_4',['nano_ble33_sense_microphone.ino',['../nano__ble33__sense__microphone_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5fmicrophone_5fcontinuous_2eino_5',['nano_ble33_sense_microphone_continuous.ino',['../nano__ble33__sense__microphone__continuous_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5frev2_5faccelerometer_2eino_6',['nano_ble33_sense_rev2_accelerometer.ino',['../nano__ble33__sense__rev2__accelerometer_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5frev2_5faccelerometer_5fcontinuous_2eino_7',['nano_ble33_sense_rev2_accelerometer_continuous.ino',['../nano__ble33__sense__rev2__accelerometer__continuous_8ino.html',1,'']]],
  ['nano_5fble33_5fsense_5frev2_5ffusion_2eino_8',['nano_ble33_sense_rev2_fusion.ino',['../nano__ble33__sense__rev2__fusion_8ino.html',1,'']]],
  ['neg_2ecc_9',['neg.cc',['../neg_8cc.html',1,'']]],
  ['neg_2ecpp_10',['neg.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcf91b7c1ceb99b20eb4a040a70fd06cda.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2neg_8cpp.html',1,'(Global Namespace)']]],
  ['neg_2eh_11',['neg.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src9c0ced520e090827b21c71bec5a554f8.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke69136fe187993a06b218fd02c1e2621a.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2neg_8h.html',1,'(Global Namespace)']]],
  ['neg_5ftest_2ecc_12',['neg_test.cc',['../neg__test_8cc.html',1,'']]],
  ['neon_5fcheck_2eh_13',['neon_check.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcba675a732f033114c5db54cebab5a525.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2keeeb064f14a6131756b8eb1cc279b9efd.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2optimized_2neon__check_8h.html',1,'(Global Namespace)']]],
  ['network_5ftester_5ftest_2ecc_14',['network_tester_test.cc',['../network__tester__test_8cc.html',1,'']]],
  ['new_5fplatform_5fsupport_2emd_15',['new_platform_support.md',['../new__platform__support_8md.html',1,'']]],
  ['nicla_5fsense_5ffusion_2eino_16',['nicla_sense_fusion.ino',['../nicla__sense__fusion_8ino.html',1,'']]],
  ['nicla_5fvision_5fcamera_2eino_17',['nicla_vision_camera.ino',['../nicla__vision__camera_8ino.html',1,'']]],
  ['nicla_5fvision_5ffusion_2eino_18',['nicla_vision_fusion.ino',['../nicla__vision__fusion_8ino.html',1,'']]],
  ['nicla_5fvision_5fmicrophone_2eino_19',['nicla_vision_microphone.ino',['../nicla__vision__microphone_8ino.html',1,'']]],
  ['nicla_5fvision_5fmicrophone_5fcontinuous_2eino_20',['nicla_vision_microphone_continuous.ino',['../nicla__vision__microphone__continuous_8ino.html',1,'']]],
  ['no_5fmicro_5ffeatures_5fdata_2ecc_21',['no_micro_features_data.cc',['../no__micro__features__data_8cc.html',1,'']]],
  ['no_5fmicro_5ffeatures_5fdata_2eh_22',['no_micro_features_data.h',['../no__micro__features__data_8h.html',1,'']]],
  ['noise_5freduction_2ec_23',['noise_reduction.c',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction_8c.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction_8c.html',1,'(Global Namespace)']]],
  ['noise_5freduction_2eh_24',['noise_reduction.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction_8h.html',1,'(Global Namespace)']]],
  ['noise_5freduction_5fio_2ec_25',['noise_reduction_io.c',['../noise__reduction__io_8c.html',1,'']]],
  ['noise_5freduction_5fio_2eh_26',['noise_reduction_io.h',['../noise__reduction__io_8h.html',1,'']]],
  ['noise_5freduction_5ftest_2ecc_27',['noise_reduction_test.cc',['../noise__reduction__test_8cc.html',1,'']]],
  ['noise_5freduction_5futil_2ec_28',['noise_reduction_util.c',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction__util_8c.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction__util_8c.html',1,'(Global Namespace)']]],
  ['noise_5freduction_5futil_2eh_29',['noise_reduction_util.h',['../tflite-micro-arduino-examples-main_2src_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction__util_8h.html',1,'(Global Namespace)'],['../tflite-micro-main_2tensorflow_2lite_2experimental_2microfrontend_2lib_2noise__reduction__util_8h.html',1,'(Global Namespace)']]],
  ['non_5fpersistent_5farena_5fbuffer_5fallocator_2ecc_30',['non_persistent_arena_buffer_allocator.cc',['../non__persistent__arena__buffer__allocator_8cc.html',1,'']]],
  ['non_5fpersistent_5farena_5fbuffer_5fallocator_2ecpp_31',['non_persistent_arena_buffer_allocator.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src886db07e814dddc05f96fa6fee3d2e87.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2non__persistent__arena__buffer__allocator_8cpp.html',1,'(Global Namespace)']]],
  ['non_5fpersistent_5farena_5fbuffer_5fallocator_2eh_32',['non_persistent_arena_buffer_allocator.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src8c81a7d46103cc34dc4e59afc4025fee.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mi47a55b8516ef5db04742956b6d5f257d.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2non__persistent__arena__buffer__allocator_8h.html',1,'(Global Namespace)']]],
  ['non_5fpersistent_5farena_5fbuffer_5fallocator_5ftest_2ecc_33',['non_persistent_arena_buffer_allocator_test.cc',['../non__persistent__arena__buffer__allocator__test_8cc.html',1,'']]],
  ['non_5fpersistent_5fbuffer_5fplanner_5fshim_2ecc_34',['non_persistent_buffer_planner_shim.cc',['../non__persistent__buffer__planner__shim_8cc.html',1,'']]],
  ['non_5fpersistent_5fbuffer_5fplanner_5fshim_2ecpp_35',['non_persistent_buffer_planner_shim.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcc5425862bf68983e2248fd1aa9d30beb.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2memory__planner_2noaf11cb3da108ce9be87889709a5aeb82.html',1,'(Global Namespace)']]],
  ['non_5fpersistent_5fbuffer_5fplanner_5fshim_2eh_36',['non_persistent_buffer_planner_shim.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcf452bf6a50a1ffed79958c311c962072.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mi6d05236d0d579023158f795b62692e4f.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2memory__planner_2no2223cfde05ea17d0b73985ece121ab3d.html',1,'(Global Namespace)']]],
  ['non_5fpersistent_5fbuffer_5fplanner_5fshim_5ftest_2ecc_37',['non_persistent_buffer_planner_shim_test.cc',['../non__persistent__buffer__planner__shim__test_8cc.html',1,'']]],
  ['none_2eh_38',['none.h',['../none_8h.html',1,'']]],
  ['numpy_2ehpp_39',['numpy.hpp',['../numpy_8hpp.html',1,'']]],
  ['numpy_5ftypes_2eh_40',['numpy_types.h',['../numpy__types_8h.html',1,'']]],
  ['numpy_5futils_2ecc_41',['numpy_utils.cc',['../numpy__utils_8cc.html',1,'']]],
  ['numpy_5futils_2eh_42',['numpy_utils.h',['../numpy__utils_8h.html',1,'']]]
];
