var searchData=
[
  ['table_2eh_0',['table.h',['../table_8h.html',1,'']]],
  ['tanh_2ecc_1',['tanh.cc',['../tanh_8cc.html',1,'']]],
  ['tanh_2ecpp_2',['tanh.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src3235c69a62905bb7b07aeea528dbaf1b.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2tanh_8cpp.html',1,'(Global Namespace)']]],
  ['tanh_2eh_3',['tanh.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcbb96f6bc7fcccba61661d363d76ae7a3.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcde372870197869a4b266fb7141a0789f.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke2c1f4526b07365a2867675d30c517900.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke2ea9f75d9b535afc3d716f8d8d26a8cb.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2integer__ops_2tanh_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2tanh_8h.html',1,'(Global Namespace)']]],
  ['tanh_5ftest_2ecc_4',['tanh_test.cc',['../tanh__test_8cc.html',1,'']]],
  ['tensaiflow_2eh_5',['tensaiflow.h',['../tensaiflow_8h.html',1,'']]],
  ['tensor_2epy_6',['tensor.py',['../tensor_8py.html',1,'']]],
  ['tensor_5fctypes_2ecc_7',['tensor_ctypes.cc',['../tensor__ctypes_8cc.html',1,'']]],
  ['tensor_5fctypes_2eh_8',['tensor_ctypes.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src73371838bf6704189d05830092261a0e.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ke1be4bd803d22062d931980b261505c5e.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2tensor__ctypes_8h.html',1,'(Global Namespace)']]],
  ['tensor_5futils_2ecc_9',['tensor_utils.cc',['../core_2api_2tensor__utils_8cc.html',1,'(Global Namespace)'],['../kernels_2internal_2tensor__utils_8cc.html',1,'(Global Namespace)']]],
  ['tensor_5futils_2ecpp_10',['tensor_utils.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src20b4ee89c36b5617cd02fcae486a30b4.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcea13529ffb46c078a1b8e30dccee44e1.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2core_2api_2tensor__utils_8cpp.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2tensor__utils_8cpp.html',1,'(Global Namespace)']]],
  ['tensor_5futils_2eh_11',['tensor_utils.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcde8000cb84ba91818f4cfaa4b0e9abcf.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2core_2api_2tensor__utils_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2core_2api_2tensor__utils_8h.html',1,'(Global Namespace)']]],
  ['tensorflowlite_2eh_12',['TensorFlowLite.h',['../_tensor_flow_lite_8h.html',1,'']]],
  ['tensorrt_2eh_13',['tensorrt.h',['../tensorrt_8h.html',1,'']]],
  ['test_5fconv_5fmodel_2ecc_14',['test_conv_model.cc',['../test__conv__model_8cc.html',1,'']]],
  ['test_5fconv_5fmodel_2eh_15',['test_conv_model.h',['../test__conv__model_8h.html',1,'']]],
  ['test_5fhelper_5fcustom_5fops_2ecc_16',['test_helper_custom_ops.cc',['../test__helper__custom__ops_8cc.html',1,'']]],
  ['test_5fhelper_5fcustom_5fops_2ecpp_17',['test_helper_custom_ops.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcbfd9c00399d83b3c16790df80ca04fac.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2test__helper__custom__ops_8cpp.html',1,'(Global Namespace)']]],
  ['test_5fhelper_5fcustom_5fops_2eh_18',['test_helper_custom_ops.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcba7b490f83f1570e0dd6cd5323b20154.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mi59a1de679e5b03c8770eb83ecaae37b9.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2test__helper__custom__ops_8h.html',1,'(Global Namespace)']]],
  ['test_5fhelpers_2ecc_19',['test_helpers.cc',['../test__helpers_8cc.html',1,'']]],
  ['test_5fhelpers_2ecpp_20',['test_helpers.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcc59498706967e367722c98198bdbde56.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2test__helpers_8cpp.html',1,'(Global Namespace)']]],
  ['test_5fhelpers_2eh_21',['test_helpers.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src585e3e0121074c94f59a7ecc740c0c25.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2test__helpers_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2test__helpers_8h.html',1,'(Global Namespace)']]],
  ['test_5fi2s_5fcodec_2eino_22',['test_i2s_codec.ino',['../test__i2s__codec_8ino.html',1,'']]],
  ['test_5foriginal_2epy_23',['test_original.py',['../test__original_8py.html',1,'']]],
  ['test_5fover_5fserial_2ecpp_24',['test_over_serial.cpp',['../test__over__serial_8cpp.html',1,'']]],
  ['test_5fover_5fserial_2eh_25',['test_over_serial.h',['../test__over__serial_8h.html',1,'']]],
  ['test_5fover_5fserial_2epy_26',['test_over_serial.py',['../test__over__serial_8py.html',1,'']]],
  ['test_5ftflite_2epy_27',['test_tflite.py',['../test__tflite_8py.html',1,'']]],
  ['test_5futils_2epy_28',['test_utils.py',['../test__utils_8py.html',1,'']]],
  ['test_5fwm8960_2eino_29',['test_wm8960.ino',['../test__wm8960_8ino.html',1,'']]],
  ['testapds9960_2eino_30',['TestAPDS9960.ino',['../_test_a_p_d_s9960_8ino.html',1,'']]],
  ['testapds9960color_2eino_31',['TestAPDS9960Color.ino',['../_test_a_p_d_s9960_color_8ino.html',1,'']]],
  ['testapds9960gesture_2eino_32',['TestAPDS9960Gesture.ino',['../_test_a_p_d_s9960_gesture_8ino.html',1,'']]],
  ['testapds9960proximity_2eino_33',['TestAPDS9960Proximity.ino',['../_test_a_p_d_s9960_proximity_8ino.html',1,'']]],
  ['testing_5fhelpers_5ftest_2ecc_34',['testing_helpers_test.cc',['../testing__helpers__test_8cc.html',1,'']]],
  ['testled_2eino_35',['TestLED.ino',['../_test_l_e_d_8ino.html',1,'']]],
  ['testledbrightness_2eino_36',['TestLEDBrightness.ino',['../_test_l_e_d_brightness_8ino.html',1,'']]],
  ['testledbuiltin_2eino_37',['TestLEDBuiltin.ino',['../_test_l_e_d_builtin_8ino.html',1,'']]],
  ['testledbuiltinapplication_2eino_38',['TestLEDBuiltinApplication.ino',['../_test_l_e_d_builtin_application_8ino.html',1,'']]],
  ['testledpower_2eino_39',['TestLEDPower.ino',['../_arduino_2_l_e_d_2_test_l_e_d_power_2_test_l_e_d_power_8ino.html',1,'(Global Namespace)'],['../_nano33_b_l_e_sense_2_test_2_test_l_e_d_power_8ino.html',1,'(Global Namespace)']]],
  ['testledpowerbattery_2eino_40',['TestLEDPowerBattery.ino',['../_arduino_2_l_e_d_2_test_l_e_d_power_battery_2_test_l_e_d_power_battery_8ino.html',1,'(Global Namespace)'],['../_nano33_b_l_e_sense_2_test_2_test_l_e_d_power_battery_8ino.html',1,'(Global Namespace)']]],
  ['testledpowerbrightness_2eino_41',['TestLEDPowerBrightness.ino',['../_arduino_2_l_e_d_2_test_l_e_d_power_brightness_2_test_l_e_d_power_brightness_8ino.html',1,'(Global Namespace)'],['../_nano33_b_l_e_sense_2_test_2_test_l_e_d_power_brightness_8ino.html',1,'(Global Namespace)']]],
  ['testledrgb_2eino_42',['TestLEDRGB.ino',['../_test_l_e_d_r_g_b_8ino.html',1,'']]],
  ['testledrgbbrightness_2eino_43',['TestLEDRGBBrightness.ino',['../_test_l_e_d_r_g_b_brightness_8ino.html',1,'']]],
  ['testledrgbcolors_2eino_44',['TestLEDRGBColors.ino',['../_test_l_e_d_r_g_b_colors_8ino.html',1,'']]],
  ['testlsm9ds1_2eino_45',['TestLSM9DS1.ino',['../_test_l_s_m9_d_s1_8ino.html',1,'']]],
  ['testmicrophone_2eino_46',['TestMicrophone.ino',['../_test_microphone_8ino.html',1,'']]],
  ['testoledssd1308_2eino_47',['TestOLEDSSD1308.ino',['../_test_o_l_e_d_s_s_d1308_8ino.html',1,'']]],
  ['testpushbutton_2eino_48',['TestPushButton.ino',['../_test_push_button_8ino.html',1,'']]],
  ['testpushbuttoninterrupt_2eino_49',['TestPushButtonInterrupt.ino',['../_test_push_button_interrupt_8ino.html',1,'']]],
  ['tflite_2dcamera_2dbutton_2epy_50',['tflite-camera-button.py',['../tflite-camera-button_8py.html',1,'']]],
  ['tflite_2dcamera_2epy_51',['tflite-camera.py',['../tflite-camera_8py.html',1,'']]],
  ['tflite_2dfoto_2epy_52',['tflite-foto.py',['../tflite-foto_8py.html',1,'']]],
  ['tflite_2dresolver_2eh_53',['tflite-resolver.h',['../tflite-resolver_8h.html',1,'']]],
  ['tflite_5feon_2eh_54',['tflite_eon.h',['../tflite__eon_8h.html',1,'']]],
  ['tflite_5fflatbuffer_5falign_2epy_55',['tflite_flatbuffer_align.py',['../tflite__flatbuffer__align_8py.html',1,'']]],
  ['tflite_5fflatbuffer_5falign_5fwrapper_2ecc_56',['tflite_flatbuffer_align_wrapper.cc',['../tflite__flatbuffer__align__wrapper_8cc.html',1,'']]],
  ['tflite_5ffull_2eh_57',['tflite_full.h',['../tflite__full_8h.html',1,'']]],
  ['tflite_5fhelper_2eh_58',['tflite_helper.h',['../tflite__helper_8h.html',1,'']]],
  ['tflite_5flearn_5f8_2ecpp_59',['tflite_learn_8.cpp',['../tflite__learn__8_8cpp.html',1,'']]],
  ['tflite_5flearn_5f8_2eh_60',['tflite_learn_8.h',['../tflite__learn__8_8h.html',1,'']]],
  ['tflite_5fmicro_2eh_61',['tflite_micro.h',['../tflite__micro_8h.html',1,'']]],
  ['tflite_5ftidl_2eh_62',['tflite_tidl.h',['../tflite__tidl_8h.html',1,'']]],
  ['tflm_5fmodel_5ftransforms_2epy_63',['tflm_model_transforms.py',['../tflm__model__transforms_8py.html',1,'']]],
  ['tflm_5fmodel_5ftransforms_5flib_2epy_64',['tflm_model_transforms_lib.py',['../tflm__model__transforms__lib_8py.html',1,'']]],
  ['tflm_5fmodel_5ftransforms_5ftest_2epy_65',['tflm_model_transforms_test.py',['../tflm__model__transforms__test_8py.html',1,'']]],
  ['tflm_5fruntime_2epy_66',['tflm_runtime.py',['../tflm__runtime_8py.html',1,'']]],
  ['tfltocarray_2epy_67',['TFLtoCArray.py',['../_t_f_lto_c_array_8py.html',1,'']]],
  ['third_5fparty_5fdownloads_2einc_68',['third_party_downloads.inc',['../third__party__downloads_8inc.html',1,'']]],
  ['tile_2ecpp_69',['tile.cpp',['../tile_8cpp.html',1,'']]],
  ['tinyekf_2ehpp_70',['tinyekf.hpp',['../tinyekf_8hpp.html',1,'']]],
  ['tinyekf_5fcustom_2eh_71',['tinyekf_custom.h',['../tinyekf__custom_8h.html',1,'']]],
  ['topk_5fv2_2ecpp_72',['topk_v2.cpp',['../topk__v2_8cpp.html',1,'']]],
  ['train_2epy_73',['train.py',['../hello__world_2train_8py.html',1,'(Global Namespace)'],['../mnist__lstm_2train_8py.html',1,'(Global Namespace)']]],
  ['trained_5fmodel_5fops_5fdefine_2eh_74',['trained_model_ops_define.h',['../trained__model__ops__define_8h.html',1,'']]],
  ['training_5fa_5fmodel_2emd_75',['training_a_model.md',['../training__a__model_8md.html',1,'']]],
  ['training_5fcifar_2epy_76',['Training_CIFAR.py',['../_training___c_i_f_a_r_8py.html',1,'']]],
  ['trainingdata_2epy_77',['TrainingData.py',['../_training_data_8py.html',1,'']]],
  ['trainingdatapart_2epy_78',['TrainingDataPart.py',['../_training_data_part_8py.html',1,'']]],
  ['trainingmodel_2epy_79',['TrainingModel.py',['../_training_model_8py.html',1,'']]],
  ['transform_5ffunctions_2eh_80',['transform_functions.h',['../transform__functions_8h.html',1,'']]],
  ['transform_5ffunctions_5ff16_2eh_81',['transform_functions_f16.h',['../transform__functions__f16_8h.html',1,'']]],
  ['transform_5fsource_2epy_82',['transform_source.py',['../transform__source_8py.html',1,'']]],
  ['transmissioncode_2eino_83',['TransmissionCode.ino',['../_transmission_code_8ino.html',1,'']]],
  ['transpose_2ecc_84',['transpose.cc',['../transpose_8cc.html',1,'']]],
  ['transpose_2ecpp_85',['transpose.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src5dc2470fb2499b5531a6cb4a01b15718.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2transpose_8cpp.html',1,'(Global Namespace)']]],
  ['transpose_2eh_86',['transpose.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src0c9568482b57c7eb64d38c07177594c8.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2ked462645484a96eb64b7d4f568cce7cbe.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2transpose_8h.html',1,'(Global Namespace)']]],
  ['transpose_5fconv_2ecc_87',['transpose_conv.cc',['../cmsis__nn_2transpose__conv_8cc.html',1,'(Global Namespace)'],['../transpose__conv_8cc.html',1,'(Global Namespace)'],['../xtensa_2transpose__conv_8cc.html',1,'(Global Namespace)']]],
  ['transpose_5fconv_2ecpp_88',['transpose_conv.cpp',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srca500b6c031a9cc477931153b5624e9aa.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2micro_2kernels_2transpose__conv_8cpp.html',1,'(Global Namespace)']]],
  ['transpose_5fconv_2eh_89',['transpose_conv.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcaf0ad825c8f1f6aedadfcdde9921e58c.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2src673025ae69b5348eeb391f717fbe7bca.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kedeecf3f8238845238e920f13e2d82add.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kea84b72597f6afa055b775cd50288bc1e.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2mifd9ae5008c3d7d5d9b32ea9ea7382ac2.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2referen912e6dbac471f411f8602f07c003d627.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2reference_2transpose__conv_8h.html',1,'(Global Namespace)']]],
  ['transpose_5fconv_5ftest_2ecc_90',['transpose_conv_test.cc',['../transpose__conv__test_8cc.html',1,'']]],
  ['transpose_5ftest_2ecc_91',['transpose_test.cc',['../transpose__test_8cc.html',1,'']]],
  ['tree_5fensemble_5fclassifier_2ecpp_92',['tree_ensemble_classifier.cpp',['../kernels_2custom_2tree__ensemble__classifier_8cpp.html',1,'(Global Namespace)'],['../micro_2kernels_2tree__ensemble__classifier_8cpp.html',1,'(Global Namespace)']]],
  ['tree_5fensemble_5fclassifier_2eh_93',['tree_ensemble_classifier.h',['../kernels_2custom_2tree__ensemble__classifier_8h.html',1,'(Global Namespace)'],['../micro_2kernels_2tree__ensemble__classifier_8h.html',1,'(Global Namespace)']]],
  ['types_2eh_94',['types.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcac6abf6cfda0e7e78c43daef9860bac1.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2kernels_2internal_2types_8h.html',1,'(Global Namespace)'],['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-main_2tensorflow_2lite_2micro_2kernels_2ceva_2types_8h.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2tensorflow_2lite_2kernels_2internal_2types_8h.html',1,'(Global Namespace)']]],
  ['tz_5fcontext_2eh_95',['tz_context.h',['../_arduino_2_get_started_with_machine_learning_on_arduino_2tflite-micro-arduino-examples-main_2srcffab91c313eb4e3c7ea7ccdfea2ceeb5.html',1,'(Global Namespace)'],['../_face___access__inferencing_2src_2edge-impulse-sdk_2_c_m_s_i_s_2_core_2_include_2tz__context_8h.html',1,'(Global Namespace)']]]
];
