var searchData=
[
  ['fast_20math_20functions_0',['Fast Math Functions',['../group__group_fast_math.html',1,'']]],
  ['field_20macros_1',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['filtering_20functions_2',['Filtering Functions',['../group__group_filters.html',1,'']]],
  ['flatbuffers_5fcpp_5fapi_3',['Flatbuffers_cpp_api',['../group__flatbuffers__cpp__api.html',1,'']]],
  ['floating_20point_20unit_20fpu_4',['Floating Point Unit (FPU)',['../group___c_m_s_i_s___f_p_u.html',1,'']]],
  ['for_20neural_20network_20computation_5',['Basic Math Functions for Neural Network Computation',['../group___n_n_basic_math.html',1,'']]],
  ['fpu_6',['Floating Point Unit (FPU)',['../group___c_m_s_i_s___f_p_u.html',1,'']]],
  ['fpu_20functions_7',['FPU Functions',['../group___c_m_s_i_s___core___fpu_functions.html',1,'']]],
  ['fully_20connected_8',['Fully Connected',['../group__support_f_c.html',1,'']]],
  ['fully_20connected_20layer_20functions_9',['Fully-connected Layer Functions',['../group___f_c.html',1,'']]],
  ['functions_10',['Functions',['../group___acti.html',1,'Activation Functions'],['../group__group_math.html',1,'Basic Math Functions'],['../group___c_m_s_i_s___core___cache_functions.html',1,'Cache Functions'],['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'CMSIS Core Register Access Functions'],['../group__group_cmplx_math.html',1,'Complex Math Functions'],['../group___concatenation.html',1,'Concatenation Functions'],['../group__group_controller.html',1,'Controller Functions'],['../group___n_n_conv.html',1,'Convolution Functions'],['../group___c_m_s_i_s___core___d_c_b_functions.html',1,'Debug Control Functions'],['../group___c_m_s_i_s___core___d_i_b_functions.html',1,'Debug Identification Functions'],['../group___d_i_s_t_a_n_c_e_f.html',1,'Distance Functions'],['../group__group_elementwise.html',1,'Elementwise Functions'],['../group__group_fast_math.html',1,'Fast Math Functions'],['../group__group_filters.html',1,'Filtering Functions'],['../group___c_m_s_i_s___core___fpu_functions.html',1,'FPU Functions'],['../group___f_c.html',1,'Fully-connected Layer Functions'],['../group__ei__functions.html',1,'Functions'],['../group__group_interpolation.html',1,'Interpolation Functions'],['../group___c_m_s_i_s__core___debug_functions.html',1,'ITM Functions'],['../group__group_matrix.html',1,'Matrix Functions'],['../group___c_m_s_i_s___core___mve_functions.html',1,'MVE Functions'],['../group__nndata__convert.html',1,'Neural Network Data Conversion Functions'],['../group__group_n_n.html',1,'Neural Network Functions'],['../group___c_m_s_i_s___core___n_v_i_c_functions.html',1,'NVIC Functions'],['../group___pooling.html',1,'Pooling Functions'],['../group__group_quaternion_math.html',1,'Quaternion Math Functions'],['../group___reshape.html',1,'Reshape Functions'],['../group___c_m_s_i_s___core___s_a_u_functions.html',1,'SAU Functions'],['../group___softmax.html',1,'Softmax Functions'],['../group__group_stats.html',1,'Statistics Functions'],['../group___s_v_d_f.html',1,'SVDF Functions'],['../group__group_s_v_m.html',1,'SVM Functions'],['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'SysTick Functions'],['../group__group_transforms.html',1,'Transform Functions']]],
  ['functions_11',['functions',['../group___basic_math.html',1,'Basic math functions'],['../group__group_distance.html',1,'Distance functions'],['../group___c_m_s_i_s___core___pac_key_functions.html',1,'PAC Key functions'],['../group__ei__user__functions.html',1,'User-defined functions']]],
  ['functions_20and_20instructions_20reference_12',['Functions and Instructions Reference',['../group___c_m_s_i_s___core___function_interface.html',1,'']]],
  ['functions_20for_20neural_20network_20computation_13',['Basic Math Functions for Neural Network Computation',['../group___n_n_basic_math.html',1,'']]]
];
