var searchData=
[
  ['c_20c_5fapi_5ftypes_20h_0',['lite/c/c_api_types.h',['../group__c__api__types.html',1,'']]],
  ['c_20common_20h_1',['lite/c/common.h',['../group__common.html',1,'']]],
  ['c_5fapi_5ftypes_20h_2',['lite/c/c_api_types.h',['../group__c__api__types.html',1,'']]],
  ['cache_20functions_3',['Cache Functions',['../group___c_m_s_i_s___core___cache_functions.html',1,'']]],
  ['clarke_20transform_4',['Clarke Transform',['../group__clarke.html',1,'Vector Clarke Transform'],['../group__inv__clarke.html',1,'Vector Inverse Clarke Transform']]],
  ['cmsis_20core_20instruction_20interface_5',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_6',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['cmsis_20global_20defines_7',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_8',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['codes_9',['Return codes',['../group__ei__returntypes.html',1,'']]],
  ['common_20h_10',['lite/c/common.h',['../group__common.html',1,'']]],
  ['compatibility_20aliases_11',['Backwards Compatibility Aliases',['../group___c_m_s_i_s__register__aliases.html',1,'']]],
  ['complex_20math_20functions_12',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['computation_13',['Basic Math Functions for Neural Network Computation',['../group___n_n_basic_math.html',1,'']]],
  ['concatenation_20functions_14',['Concatenation Functions',['../group___concatenation.html',1,'']]],
  ['configuration_20information_20registers_20implementation_20defined_15',['Processor Configuration Information Registers (IMPLEMENTATION DEFINED)',['../group___prc_cfg_inf___type.html',1,'']]],
  ['connected_16',['Fully Connected',['../group__support_f_c.html',1,'']]],
  ['connected_20layer_20functions_17',['Fully-connected Layer Functions',['../group___f_c.html',1,'']]],
  ['control_18',['PID Motor Control',['../group___p_i_d.html',1,'']]],
  ['control_20block_19',['Debug Control Block',['../group___c_m_s_i_s___d_c_b.html',1,'']]],
  ['control_20block_20register_20icb_20',['Implementation Control Block register (ICB)',['../group___c_m_s_i_s___i_c_b.html',1,'']]],
  ['control_20block_20scb_21',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['control_20functions_22',['Debug Control Functions',['../group___c_m_s_i_s___core___d_c_b_functions.html',1,'']]],
  ['control_20registers_23',['Control Registers',['../group___pwr_mod_ctl___type.html',1,'Power Mode Control Registers'],['../group___c_m_s_i_s___c_o_r_e.html',1,'Status and Control Registers']]],
  ['control_20registers_20implementation_20defined_24',['Memory System Control Registers (IMPLEMENTATION DEFINED)',['../group___mem_sys_ctl___type.html',1,'']]],
  ['controller_20functions_25',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['controller_20nvic_26',['Nested Vectored Interrupt Controller (NVIC)',['../group___c_m_s_i_s___n_v_i_c.html',1,'']]],
  ['controller_20registers_27',['External Wakeup Interrupt Controller Registers',['../group___e_w_i_c___type.html',1,'']]],
  ['controls_20not_20in_20scb_20scnscb_28',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['conversion_29',['Data Conversion',['../group__support_conversion.html',1,'']]],
  ['conversion_20functions_30',['Neural Network Data Conversion Functions',['../group__nndata__convert.html',1,'']]],
  ['convolution_31',['Convolution',['../group__support_convolution.html',1,'']]],
  ['convolution_20functions_32',['Convolution Functions',['../group___n_n_conv.html',1,'']]],
  ['core_20debug_20registers_20coredebug_33',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['core_20definitions_34',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20instruction_20interface_35',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['core_20register_20access_20functions_36',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['core_20register_20bit_20field_20macros_37',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['coredebug_38',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['cosine_39',['Sine Cosine',['../group___sin_cos.html',1,'']]]
];
